### ISSUE TITLE
RE: image attachments in Collector

### ISSUE THREAD

**Issue by DerekLaw** [doug-m/CollectorAuroraTesting#10]
### Issue
This is not an issue, more of a question and perhaps help doc enhancement

When I view an attachment for a feature in Collector, and I click the cloud icon to "download" it - where is this attachment stored? Is it on my device local cache? This is my expectation, but when I read this devdoc page:

http://docdev.arcgis.com/en/collector/windows/collect-data/work-with-attachments.htm#ESRI_SECTION1_DB75048A82424CA3AF4E3C3F28D9F027

There is a section called "Save an attachment to your device" which confuses me, because I thought I already downloaded the attachment when I clicked the cloud icon. Sorry if I am missing something obvious.

Can some info be added to the help doc to tell me where the attachment is after I click the cloud icon?

### Expected Behavior
N/A

### Map and Credentials
N/A
### Device Information
* Device: iPhone 7
* OS Version: 11.2.6

After I click the cloud icon to "download" the attachment, I think it is already on my device, no?

![image-1](https://user-images.githubusercontent.com/1037228/38382431-ce1358a8-38be-11e8-8921-37639cf13922.jpg)

**Comment by kyliedonia** [comment]
It is on your device in the app, but it's not saved as an image on your device that you can access outside the app. I'll think about how to make that more clear in Aurora doc :)

**Comment by kyliedonia** [comment]
Included notes in the in-progress Aurora doc.
