### ISSUE TITLE
Allow user to specify area size in ad-hoc workflow

### ISSUE THREAD

**Issue by mschenker** [doug-m/CollectorAuroraTesting#103]
### Issue
In the ad-hoc offline case, there is currently no way for the user to specify a smaller area than chosen by the system. It will automatically default to the largest extent possible as defined by the app. This leads to unnecessary downloads and delays in cases where a much smaller area would be enough.

### Expected Behavior
The user should still be able to define a much smaller map area.

### Map and Credentials

* Group Name:EsriSwitzerland2AuroraHolistic
* Map Name:SwissImageWebMerc

### Device Information
* Device:iOS
* OS Version:11.3.1

**Comment by Kevin-GIS** [comment]
Just for clarification, you're zoomed in past what you set for LOD and are getting a larger area than what you zoomed into. Is that correct?

**Comment by mschenker** [comment]
Hi Kevin, correct. I want to download an area that is smaller than what I get automatically picked for my LOD.

**Comment by Kevin-GIS** [comment]
@mschenker can you please share a video of your workflow?

**Comment by mschenker** [comment]
OK, I now understand what you wrote in your previous comment: You get less data when you zoom in further, the grey box is only relevant if you are zoomed out beyond this. --> Blame it on user error unless you agree that it could be a usability thing ;-)

**Comment by doug-m** [comment]
Closing for now, working as designed.
