### ISSUE TITLE
Photos and video attachments taken from Collector Aurora are rotated when downloaded from popup in Portal 10.6. map.

### ISSUE THREAD

**Issue by dmoorevt87** [doug-m/CollectorAuroraTesting#11]
### Issue
When adding images and videos from Collector aurora (videos and photos taken inside the app in portrait mode), the resulting images and videos are rotated when viewing them in a web map (Portal 10.6).

### Expected Behavior
Photos should not be rotated regardless of the orientation they were taken in. 

### Map and Credentials

https://csc-squalls10l2.esri.com/portal
siteadmin/siteadmin1

https://csc-squalls10l2.esri.com/portal/home/item.html?id=a956b3050185421394c3b3e4fe702198

### Steps to Reproduce
Add a point and add a photo/video. Can be submitted over the air or via sync.

### Device Information
* Device: iPhone 7 Plus
* OS Version: iOS 11.3

**Comment by bethanyw** [comment]
Seeing the same behavior in Enterprise 10.5.1

**Comment by dmoorevt87** [comment]
I also added two images - one that I saved onto my phone from a web site and one that I took on my phone a couple months ago. The saved image was not rotated, but the one that was taken on my phone was. This also is an issue with attached images and not just taking the photo in Collector

**Comment by miaogeng** [comment]
Interestingly, I added one feature with three attachments (one landscape mode, two portrait mode) Object ID 15. Downloaded image looks fine to me. I am wondering if it is related to the app used for opening the photos in Windows machine.

**Comment by miaogeng** [comment]
@dmoorevt87 @bethanyw i can't reproduce the issue. Maybe during next holistic event, you can show me the issue if it is reproducible for you.
