### ISSUE TITLE
Domain Descriptions Not passing to form correctly

### ISSUE THREAD

**Issue by mudnmaps** [doug-m/CollectorAuroraTesting#112]
### Issue
Domain Descriptions Not passing to form correctly - shows up in the picklist but doesn't in the form after something is chosen.

### Expected Behavior
I would expect when someone picks something from the form list when collecting a data element, that when one sees the domain description in the picklist that that description would propagate over to the form after selected like it does in the current version of collector

### Map and Credentials
* Group Name: ESRI test group
* Map Name: Collector_Aurora
This map was loaded this morning from a geodatabase to AGOL. It has related tables, labels, and several layers as well as one layer that isn't editable but isn't showing up on the map either.  This also persists for live maps that are running from Oracle SDE.  I don't have that map shared to the group yet.

### Steps to Reproduce
Opened the map
Created a new record
Started working through the form picking from the domain driven picklists
The picklists show the domain description, but when you select something and go on to the next field in the form, only the domain code passes through not the description.

### Device Information
•	Device: IPad Air2, IPad Air
•	OS Version: iOS 11.4 for both devices

![domainissue1](https://user-images.githubusercontent.com/19308681/41558954-35325628-7308-11e8-8d4a-95de85e3c375.jpg)
![domainissue2](https://user-images.githubusercontent.com/19308681/41558955-3558a292-7308-11e8-855f-c411d3018e4f.jpg)

**Comment by Kevin-GIS** [comment]
Similar to SF 883

**Comment by Kevin-GIS** [comment]
@mudnmaps When selecting a feature template when collecting a new feature, are the template names also displaying the codes?

**Comment by mudnmaps** [comment]
@Kevin-GIS I'm not sure I follow your question.  I don't understand what you mean by template names?

**Comment by Kevin-GIS** [comment]
Sorry for the confusion @mudnmaps. I was able to open your map and confirm that wasn't the issue. 

Here is a screenshot of what I was referring to. When you collect a new feature and choose a template to edit with:
![image-1](https://user-images.githubusercontent.com/24723464/41562923-efb9a376-7302-11e8-8d36-ad98a1b36ff7.jpg)

**Comment by Kevin-GIS** [comment]
Logged SF 993

**Comment by mudnmaps** [comment]
This also appears to be resolved with the latest push of Aurora.  Thanks!!
