### ISSUE TITLE
C23 - Open WebMap fails with Invalid XML

### ISSUE THREAD

**Issue by trichtl** [doug-m/CollectorAuroraTesting#113]
Dear Esri-Team,

Software: Collector
Version : Build 2284
OS      : iOS 11.4, iPad Air 2

Description:

we have a webmap, based on services from another organisation, which displays fine in ArcGIS Online MapViewer and also in ArcGIS Pro.
When opening the WebMap within Collector we got the message "Unable to Open Map - Invalid XML"

URL for WebMap: https://austria.maps.arcgis.com/home/webmap/viewer.html?webmap=ed376ce165aa4ee9954c096a70634589

Attached the screenshots to repro the problem.

Best regards,

Gerhard "Luigi" Trichtl
[bug.docx](https://github.com/doug-m/CollectorAuroraTesting/files/2112833/bug.docx)
[bug.txt](https://github.com/doug-m/CollectorAuroraTesting/files/2112834/bug.txt)

**Comment by Kevin-GIS** [comment]
Reproduced the issue and logged SF 980.

Reproducible in Explorer

Not reproducible in Collector Classic.

**Comment by trichtl** [comment]
ReTest with Build 2358 - still there - just as info

**Comment by trichtl** [comment]
Retest with Build 2440 and still Fails to Display, but works within Pro and Onlineviewer without an error.
We checked in Explorer and also in Runtime 100.3 on iOS 12 and so we assume it's a core Runtime Issuee handling this Webmap correctly.

**Comment by trichtl** [comment]
@Kevin-GIS as we got close to final I retested and still exists - but as it exists within Explorer as well and we have case similar Problem with poor Runtime we assume it is a Core Runtime SDK issue.

**Comment by Kevin-GIS** [comment]
Thanks for the feedback @trichtl 

Yes this is still a known issue at the runtime level.

**Comment by Kevin-GIS** [comment]
This issue has been addressed and should be available in the next app update.

Closing this issue.
