### ISSUE TITLE
Map is listed twice in when there are multiple offline areas downloaded and one has been opened. 

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#114]
### Issue
Map is listed twice when there are multiple offline areas downloaded and one has been opened. The recently opened offline area is also listed under "current" (3 instances of the same map are visible in the pick list). 
![img_0132](https://user-images.githubusercontent.com/15009559/41559627-683fc8e8-72f9-11e8-96ba-60edbb219561.PNG)

### Expected Behavior
There should only be one listing per map on the home page. If each offline map must be listed it should display the offline area name, not the Web Map name to avoid appearing as duplicates.

### Map and Credentials

* Group Name: Collector Holistic 6/18
* Map Name: Zion_vector_streets

### Steps to Reproduce
1. Download to different offline areas for a map
2. Open one of the offline areas
3. Go back to the maps screen, the name of the map will be listed twice under Recent Items and the name of the offline area opened is listed under Current.
4. Clicking either of the map items will take you to offline area selection as expected.

### Device Information
* Device: iPhone 6s
* OS Version: 11.3

**Comment by caro7202** [comment]
Issue logged SF 973

**Comment by Kevin-GIS** [comment]
This issue has been addressed.
