### ISSUE TITLE
False 'sync succeeded' message when failing to sync

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#117]
### Issue
After collecting offline edits and attempting to sync, I received an "sync succeeded" message along with a green check mark indicating success. This quickly went away and back to "Not synced - 1 local edit". I noticed I had not yet connected back to the wifi network meaning I could not sync but if I was not paying attention I might have assumed I synced my edits successfully. 

### Expected Behavior
I should get an error if I am not connected to a network in order to sync. 

### Map and Credentials
Reproduce with any offline map?

### Steps to Reproduce
1. Download map for offline use
2. Turn on airplane mode on the device
3. Collect a feature
4. Tap the sync button. You will briefly get a "sync succeeded" message along with a green check mark. 

### Device Information
* Device: Iphone 6s
* OS Version: 11.3
[ScreenRecording_06-18-2018 13-25-41.zip](https://github.com/doug-m/CollectorAuroraTesting/files/2112906/ScreenRecording_06-18-2018.13-25-41.zip)

**Comment by Kevin-GIS** [comment]
Reproduced and logged SF 982

**Comment by Kevin-GIS** [comment]
This issue has been addressed.
