### ISSUE TITLE
Download issue - unknown download error occurred

### ISSUE THREAD

**Issue by mudnmaps** [doug-m/CollectorAuroraTesting#119]
### Issue
Attempted a third app to do a download and got unknown download error occurred

### Expected Behavior
I would expect the map to actually download... 

### Map and Credentials
Group Name: ESRI test group
Map Name: Lighting V2
This is from one of our live Oracle SDE Apps

### Steps to Reproduce
In the group we clicked on ... When you click on the dots it says: Map Details, Add Offline Area, and Reload Map
The default location size is Room (these are weird sizes that don't really match their names)
clicked the button to start downloading - Download Area
The circle filled in slowly for 5 minutes and then an error popped up "Unknown download error occured"

### Device Information
* Device: IPad Air2
* OS Version: iOS 11.4

![downloadissuetake3](https://user-images.githubusercontent.com/19308681/41561525-c3121602-730f-11e8-8814-a639fb147b6e.jpg)

**Comment by Kevin-GIS** [comment]
@mudnmaps would you be able to share credentials for me to be able to access the secured services in the Lighting V2 map?

**Comment by mudnmaps** [comment]
sure.  are you at the logging in to AGOL screen or the second prompt where you have a userID and password?  I can text them to you but we don't have generic ones only ones assigned to specific people.  I wondered if that'd come up if you tested it.

**Comment by Kevin-GIS** [comment]
Thanks @mudnmaps. Yes that is correct. The second prompt are the credentials I am referring to. You can feel free to email them to me at kburke@esri.com.

**Comment by Kevin-GIS** [comment]
Thanks for the credentials @mudnmaps 

I reproduced the issue and logged SF 992

**Comment by Kevin-GIS** [comment]
@mudnmaps Can you still reproduce this issue in the latest Aurora Beta build 2338?

Also the Lightning V2 map data is inaccessible in the map you shared with the ESRI Test Group.

**Comment by Kevin-GIS** [comment]
Hi @mudnmaps 

If you're still running into this issue, please let me know. 

For the time being I am going to close this issue. Currently the maps I originally tested this issue with, and reproduced it with, are no longer available in the group you originally created for us.
