### ISSUE TITLE
Use an Esri basemap with ArcGIS Enterprise-- different behavior than previous versions

### ISSUE THREAD

**Issue by bethanyw** [doug-m/CollectorAuroraTesting#12]
### Issue
In previous versions of Collector, it was necessary to use a certain workflow to use Esri basemaps for offline use in ArcGIS Enterprise. This involved adding the basemap as an item and storing credentials.

Doc: https://doc.arcgis.com/en/collector/windows/create-maps/offline-map-prep.htm#ESRI_SECTION1_5ED9DA9CD8D14EEC8E6D34235AA62253

However, at this version, I saw that it was not necessary to do this. I attempted to download the map without using the above workflow. I was prompted for credentials from 

https://arcgis.com/sharing/rest

I entered my AGOL credentials without using proper uppercase/lowercase for my username. This failed. So then I used my exact username with the uppercase/lowercase letters and I was able to proceed.

If this is the new behavior-- we would need a doc update, and I would suggest in the prompt for credentials that it should say that it's looking for your AGOL username/password and that it's case sensitive.

### Expected Behavior
I would expect that you would have to use this workflow still, but this does not appear to be the case:

https://doc.arcgis.com/en/collector/windows/create-maps/offline-map-prep.htm#ESRI_SECTION1_5ED9DA9CD8D14EEC8E6D34235AA62253

### Map and Credentials

N/A

### Device Information
* Device: iPhone 6+
* OS Version: 11.x

**Comment by miaogeng** [comment]
@bethanyw This is not a new behavior. In Collector classic, you can also do the same thing and sign in AGOL account and download. But we don't expect the workflow to be a common one. We recommend the workflow in the doc site.

**Comment by miaogeng** [comment]
Meanwhile we will improve the prompt dialog for AGOL username/password in ArcGIS Enterprise.

**Comment by miaogeng** [comment]
@kyliedonia what do you think of this doc update request to include another workflow of using AGOL basemap in ArcGIS Enterprise?

**Comment by kyliedonia** [comment]
Is there a reason to choose the other workflow, or is it a time when there are two ways to do the same thing?

**Comment by Kevin-GIS** [comment]
This issue has been addressed.
