### ISSUE TITLE
C11 - Take Offline hangs for long time or crashes the App

### ISSUE THREAD

**Issue by trichtl** [doug-m/CollectorAuroraTesting#13]
### Issue
Version: Build 2203
OS     : iPad, iOS 11.2.6

we have a Map within ArcGIS Pro a map and publish this map as a webMap with Sync enabled on the featureservice.

webMap could be opened and displayed in Collector,  but when taken offline it starts downloading, but stays for ever at that stage (wait approx 5 minutes).

see attached screenshots and data to repro the problem.

### Expected Behavior
Download should work, but not Crash the App

### Map and Credentials
ArcGIS Online - holistic_user10 (from the Holistic Lab)
Name OffEdit_20180405

### Steps to Reproduce

* Open ArcGIS Pro-Project
* Publish to ArcGIS Online with Sync enable
* Download in Colloector
* in same cases it crashes the app also

### Device Information
* Device: iPad
* OS Version: iOS 11.2.6
[C11.zip](https://github.com/doug-m/CollectorAuroraTesting/files/1881174/C11.zip)

**Comment by dmoorevt87** [comment]
I am seeing the same thing, but it depends on the level of detail. Which level of detail are you trying to download?

**Comment by trichtl** [comment]
First Street-Level - hangs
Town-Level - crashes
City-Level - crashes

**Comment by Kevin-GIS** [comment]
Existing issue SF 738

**Comment by sbubka94** [comment]
Still an issue at 2238

Took offline area at Streets level - been hanging for over 10 minutes so far

**Comment by trichtl** [comment]
Tested now with Build 2284 - now it starts downloading, goes to 100 % and finally collector crashes

**Comment by trichtl** [comment]
Just retested with Build 2358 - as this simple map with a few feature crashes in taken offline Question is how should this work with much more feature and complex symbology

**Comment by Kevin-GIS** [comment]
@trichtl 

In the current Aurora beta build 2418, the app no longer crashes when downloading this map. 

However you will receive a 'Download Error. Failed to create replica. Please check your parameters.' error instead.

This is a known issue logged with the AGOL team regarding the layer names of Straße and Sym_äöü containing invalid characters not supported in the SQLite geodatabase. Renaming those layers is the workaround.

**Comment by Kevin-GIS** [comment]
@trichtl Thanks for the feedback. Yes, we are aware of this issue and are working with the AGOL team to get it addressed.

**Comment by trichtl** [comment]
@Kevin-GIS - Retested with Build 2469 - still Fails - after 12.5 % it stopps and Message with No Offline Areas is comming, doesn't matter which zoom Level we use

**Comment by Kevin-GIS** [comment]
Thanks for the feedback @trichtl 

The issue you're seeing is actually a create replica failed error, that is a known issue reported to AGOL. The issue is with the special characters in the layer names. Hopefully this will be addressed in the December release of AGOL.
