### ISSUE TITLE
Crash when Filter is Applied

### ISSUE THREAD

**Issue by MKellyEsri** [doug-m/CollectorAuroraTesting#130]
### Issue
Crash: https://www.youtube.com/watch?v=y0ugTECRym4

### Steps to Reproduce
Open Collector Aurora
Search by Map - e.g. Collector Testing
Create new map in ArcGIS Online which would appear with the same search
Refresh screen to load newly added map
Collector crashes

### Expected Behavior
Newly created map gets added to list

### Device Information
* Device: Apple iPhone 6
* OS Version: 11.4

**Comment by Kevin-GIS** [comment]
Logged SF 979

**Comment by Kevin-GIS** [comment]
This should be addressed in the upcoming Beta version. Testing on my end, I couldn't reproduce this issue.

**Comment by MKellyEsri** [comment]
Great stuff - thanks for the update Kevin!
