### ISSUE TITLE
Arcade - Expression Titles within Popup

### ISSUE THREAD

**Issue by MKellyEsri** [doug-m/CollectorAuroraTesting#131]
### Issue
expression/expr0, expression/expr1, etc. comes through as title for Arcade expression instead of the specified expression title in popup as in image below:

![img_3627](https://user-images.githubusercontent.com/9192183/41590358-b7abc5c0-73ae-11e8-8e6b-2b27f6d69c49.PNG)

### Expected Behavior
Arcade expression title is displayed as in webmap:

![webmapview](https://user-images.githubusercontent.com/9192183/41590162-3e968a1c-73ae-11e8-84e1-6dc0350dd511.png)

### Map and Credentials

* Group Name: Collector Aurora Feedback
* Map Name: Collector Aurora Testing - Google Maps Hyperlinks via Arcade

### Steps to Reproduce
Open Web Map
Click on Point to see Popup

### Device Information
* Device: Apple iPhone 6
* OS Version: 11.4

**Comment by doug-m** [comment]
Entered sf 988

**Comment by Kevin-GIS** [comment]
This issue has been addressed. Closing this issue.
