### ISSUE TITLE
Preparing Map Areas with Imagery in QA

### ISSUE THREAD

**Issue by MKellyEsri** [doug-m/CollectorAuroraTesting#137]
### Issue
I have been finding it difficult to pre-plan work areas with imagery as the basemap in the Early Adopter version of ArcGIS Online. As can be seen in [this video](https://www.youtube.com/watch?v=r0Wmr8KXhcw), a call is made to the packagingqa server with invalid parameters, after which everything appears to stall (no further requests are made).

### Expected Behavior
Map Area should be packaged and available for use in Collector Aurora

### Map and Credentials
Any map with Esri World Imagery and hosted Feature Layer

### Steps to Reproduce
Generate a New Map Area which contains Esri World Imagery

### Device Information
* Device: Latest Chrome Version
* OS Version: Windows 10

**Comment by doug-m** [comment]
@MKellyEsri did you use the imagery basemaps in the QA organization used in the holistic test event?

**Comment by MKellyEsri** [comment]
Hi @doug-m - I was working from the https://earlyadopters.mapsqa.arcgis.com site (as opposed to the https://esriapps.mapsqa.arcgis.com / https://g11n-test.mapsqa.arcgis.com sites) with Imagery from the Basemap Gallery. Which one should I test pre-planning from?

**Comment by Kevin-GIS** [comment]
@MKellyEsri I am going to go ahead and close this issue now that ArcGIS Online has recently been upgraded to support the Pre-planned workflows. Therefore you no longer need to use those QA orgs above. 

If you're part of the Beta program, please test out that pre-planned workflow and provide any feedback through the Early Adopter site.  

We also just recently sent out an updated Beta version. 

Thanks
