### ISSUE TITLE
"Unable to Open Map" - Need diagnosis and better workflow for fixing

### ISSUE THREAD

**Issue by btpschroeder** [doug-m/CollectorAuroraTesting#138]
### Issue
For some of my maps (which worked in previous versions of Collector), I'm receiving this error: `Unable to Open Map: The version of the map is not supported in Collector. You can upgrade the map to a supported version by resaving it`. These maps were created in (and probably haven't been touched since) 2017.

I mentioned this a bit on Slack yesterday, but I think formally logging it as an issue is important. This would be a big blocker to me potentially recommending Aurora to our client.

Saving the maps does fix the issue, but going through and individually re-saving each map on the Enterprise instance just isn't feasible. 

These particular items I'm working with were generated in mid-to-late 2017, so it is seems strange that they would be affected by SDK changes that took place in 2016, as was suggested.

Regardless of where the problem is coming from (though that is important to diagnose, if only so we can take it into account on our end when developing), dealing with this error is very user-unfriendly for field workers. They are often out in the field with limited connectivity, and are almost _never_ the person who controls the item in Portal. The nature of their work is also quite time-sensitive. I can imagine running into this issue constantly would lead to the client resenting our products, especially when these maps stopped working seemingly out of nowhere.

Potential solution: automatically re-saving the map?

### Expected Behavior
Ideally, the maps would open and function just as seamlessly as they do in the current version of Collector.

### Map and Credentials
Can provide metadata and other info upon request. Can also provide the REST API requests we're making to dynamically generate these maps and feature services, but would have to get approval from my project manager first. Just let me know.

### Steps to Reproduce
N/A

### Device Information
* Device: iPhone 8 (64GB)
* OS Version: iOS 11.4

![image_from_ios](https://user-images.githubusercontent.com/19781811/41604550-834cb8b2-73ad-11e8-9702-d782176eeb5a.png)

**Comment by doug-m** [comment]
@btpschroeder this is not an app-specific implementation, but rather a runtime limitation on apps built using the latest ArcGIS Runtime SDKs (100.x).  This is already present in Explorer for ArcGIS, and Workforce for ArcGIS. Here are the [runtime release notes](https://developers.arcgis.com/net/latest/ios/guide/release-notes-100-0-0.htm#ESRI_SECTION1_910A9F432FAB47A78ACD89F608748DD1) documenting this limitation.  

We are improving the messaging a bit in an upcoming beta update for Aurora, but we will not be able to open these web maps.  

As far as the details of how can avoid this when creating programmatically, reach out to me directly so we can discuss specifics.
