### ISSUE TITLE
App Crash When Removing Offline Area

### ISSUE THREAD

**Issue by shaelyni** [doug-m/CollectorAuroraTesting#139]
### Issue
App is crashing whenever refreshing the homepage after deleting an offline area.

### Steps to Reproduce
1. Download offline area of map.

2. Return to homepage of app.

![offlinemap-photo1](https://user-images.githubusercontent.com/40397317/41605819-bd3cdc36-73d1-11e8-91ec-2d441186d244.jpg)

3. Click on ellipsis icon to the right of the current downloaded map.

4. Select remove area.

![offlinemap-photo2](https://user-images.githubusercontent.com/40397317/41605821-bd59e1b4-73d1-11e8-8937-779fd16ea869.jpg)

5. Application returns to homepage and then crashes.

6. Re-open application and the "recent items" are reset.

![offlinemap-photo3](https://user-images.githubusercontent.com/40397317/41605822-bd79dc26-73d1-11e8-9a07-fbae6be24c46.jpg)

### Device Information
* Device: iPhone 8 Plus
* OS Version: iOS 11.4

**Comment by Kevin-GIS** [comment]
Closing as a duplicate issue of https://github.com/doug-m/CollectorAuroraTesting/issues/104
