### ISSUE TITLE
Clarification on expected behavior when removing a map that was downloaded

### ISSUE THREAD

**Issue by bethanyw** [doug-m/CollectorAuroraTesting#14]
### Issue
In previous versions of Collector, when removing a map that had been downloaded for offline use, the user had the option of whether they wanted to remove just the data, or the basemap and the data. Is this still possible? When removing the map it didn't present me with any options. This may be expected in Aurora but may be confusing for previous Collector users.

### Steps to Reproduce

1) Download the map for offline use
2) Remove the map-- user isn't provided with options about what they would like to remove

### Device Information
* Device: iPhone 6+
* OS Version: 11.x

**Comment by doug-m** [comment]
This behavior is by design.  We are trying to keep the map concept unified during both the download and the management/remove activities.  We will still support some "shared" basemap concepts, though they are not implemented yet.
