### ISSUE TITLE
Download Error: Unsupported Layer Type

### ISSUE THREAD

**Issue by shaelyni** [doug-m/CollectorAuroraTesting#140]
### Issue
Unable to download an offline map that we are using in the current version of Collector. Gives error of "unsupported layer type" but no further information as to resolution.

### Expected Behavior
This same map supports offline use in current version of Collector. Imagery basemap is being used so should not be part of current known issues with certain types of basemaps.

### Steps to Reproduce
1. Opened map in application and zoomed into small area. Layer of detail: Buildings

![dowloadissue-1](https://user-images.githubusercontent.com/40397317/41606230-b914016a-73d2-11e8-8f97-5cb6c7af2375.jpg)

2. Waited for download of offline area.

![dowloadissue-2](https://user-images.githubusercontent.com/40397317/41606231-b935efaa-73d2-11e8-9680-d3e34f9d250a.jpg)

3. After 7 minutes of waiting for the small area to download, once the download circle showed it as being almost complete, received error: unsupported layer type.

![dowloadissue-3](https://user-images.githubusercontent.com/40397317/41606232-b94ea1d0-73d2-11e8-8546-553da183dbe3.jpg)

### Device Information
* Device: iPhone 8 Plus
* OS Version: iOS 11.4

**Comment by Kevin-GIS** [comment]
@shaelyni Can you share the map with me?

**Comment by shaelyni** [comment]
@Kevin-GIS - here is the link to the AGOL map: http://arcg.is/1GPaSv

It is using secured services, but is a dev. version of an application. We have a testing username and password you can use. If you can email me at shaelyn.hill@dot.ohio.gov I can provide it for you.

**Comment by Kevin-GIS** [comment]
@shaelyni I have been testing this issue for a while and haven't been able to reproduce the error. I tried replicating the same offline area extent and detail, but it was able to download successfully. 

Can you still reproduce this issue in Aurora using the map you shared with me?

Thanks

**Comment by Kevin-GIS** [comment]
Closing this issue as non-reproducible. The map is also no longer accessible for testing.
