### ISSUE TITLE
OFFLINE FEATURE COLLECTION

### ISSUE THREAD

**Issue by cskeating** [doug-m/CollectorAuroraTesting#144]
### Issue
After collecting a new feature and filling out attributes, the add feature button no longer works. nothing happen when attempting to add another feature. 

### Expected Behavior
To be able to collect another feature. 

### Map and Credentials
The map is on our Portal and works fine to collect and sync and attach as well as scan QR codes. Just cant collect a second feature. 

* Group Name:
* Map Name:

### Device Information
* Device: IPhone 6 
* OS Version: 11.2.5

**Comment by Kevin-GIS** [comment]
@cskeating is this issue still reproducible in the current Beta version?

**Comment by cskeating** [comment]
Not this morning. I was able to collect another feature after collecting the first with QR code and all as mentioned above. They also synced back up properly to our enterprise feature services as expected.

**Comment by Kevin-GIS** [comment]
Closing this issue as non-reproducible.
