### ISSUE TITLE
Enhancement - Add QR Code search after assigning for asset inspections

### ISSUE THREAD

**Issue by cskeating** [doug-m/CollectorAuroraTesting#145]
### Issue
Need to be able to search via the camera to scan a code on an asset out in the field, such as for inspection purposes. 

### Map and Credentials

* Group Name:
* Map Name:

### Device Information
* Device:
* OS Version:

**Comment by cskeating** [comment]
This will allow for ease of pulling up a record if you are standing in front of a tagged asset

**Comment by doug-m** [comment]
@cskeating thanks for the feedback; we'll support this in a upcoming beta update.

**Comment by cskeating** [comment]
Great, thank you, Sir.

**Comment by doug-m** [comment]
Logged as sf 932

**Comment by li2504** [comment]
@cskeating This bug is fixed in the Aurora daily build. You should see it working in the next beta update.
