### ISSUE TITLE
Add ability to limit collection of new features to only related layers

### ISSUE THREAD

**Issue by rgrotefend** [doug-m/CollectorAuroraTesting#147]
### Issue
Add ability to limit collection of new features to only related layers

### Expected Behavior
Use Case: when our field staff collects new features, they should all be associated with a related, non-editable features. Limiting the ability to collect random, non-related features would be a nice addition.

### Map and Credentials
N/A

### Device Information
N/A

**Comment by doug-m** [comment]
@rgrotefend to clarify, you're hoping to limit collection of new destination features to those that are accessed through a parent (origin) feature?

Does the `filter types` setting in Collector today meet those requirements?

**Comment by rgrotefend** [comment]
@doug-m Yes, in collector classic on an iPhone (iOS 11.4) the "filter related types" functions properly and I am not able to collect non-related features. However, in collector classic on an iPad (iOS 11.3) the same "filter related types" does not function properly. The same map and features were used on both devices.This may be a known classic issue.

As for Aurora, I did not see a "filter related types" option

**Comment by doug-m** [comment]
Thanks @rgrotefend.  We do have a known issue with `Filter Types` in the current release on iOS; this will be addressed in a update later this month.

You are correct, similar setting is not present in Aurora.

**Comment by kyliedonia** [comment]
The "Show related types" setting released added in the 19.1.0 update of Collector on iOS.
