### ISSUE TITLE
Preplanned area's reported size differs pre and post download

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#152]
### Issue
Before downloading a preplanned work area in Collector, it reports a size in the hundreds of bytes. After downloading it reports the more realistic size around 100mb. 

### Expected Behavior
This should report a more accurate estimate of file size before downloading so the user is aware of the space required.

### Map and Credentials

* Group Name: Shared with holistic testing QA organization
* Map Name: CollectorPreplanned

### Steps to Reproduce
1. Create a preplanned area in ArcGIS Online
2. Open Collector and access the Web Map offline areas screen
3. Note how the size differs before downloading and after.

### Device Information
* Device: Iphone 6s
* OS Version: 11.3
![img_0135](https://user-images.githubusercontent.com/15009559/41620598-09b63a3e-73bf-11e8-97d5-c59125359fac.PNG)
![img_0134](https://user-images.githubusercontent.com/15009559/41620599-09d70886-73bf-11e8-84b5-64a7dfd9d794.PNG)

**Comment by Kevin-GIS** [comment]
This issue has been addressed. SF 989
