### ISSUE TITLE
No Sync Info Under Map Details for Map Area

### ISSUE THREAD

**Issue by JCox-Williams** [doug-m/CollectorAuroraTesting#153]
### Issue
For an offline map area I downloaded, I performed several edits and synced those edits back to Portal.  Afterwards there was no information regarding that sync operation in the map details under the specific map area I was working with.

The only location I was able to find info about last sync was within the map itself, under the sync pane.

### Expected Behavior
Have last sync info on the map area card or in map details for that map area, and not just within the sync pane within the map.

### Map and Credentials
My organizations Portal.

### Device Information
* Device: iPhone 6+
* OS Version: 11.2.2

![image](https://user-images.githubusercontent.com/40366772/41621627-75dbc7b4-73ca-11e8-9d73-c0315bf4d295.png)

**Comment by Kevin-GIS** [comment]
Addressed in SF 843 and 954. The map card will display information regarding when the last sync occurred for the offline area.

Closing this issue.
