### ISSUE TITLE
Crashing when trying to Add Offline Area

### ISSUE THREAD

**Issue by yapiyapo** [doug-m/CollectorAuroraTesting#154]
### Issue

When I click on the three dots then click on "Add Offline Area." Before I could click on the "Download Area." It crashes. 
### Expected Behavior
 I would expect it would not crash.

### Map and Credentials

* Group Name:
* Map Name:

### Device Information
* Device: iPhone 5s
* OS Version: Version 11.3

![download area](https://user-images.githubusercontent.com/6778144/41623663-ff0ffc8e-7402-11e8-8baf-20f00a8d9a72.PNG) ![data](https://user-images.githubusercontent.com/6778144/41623675-045c72b2-7403-11e8-9898-40258b633e22.PNG) ![crash](https://user-images.githubusercontent.com/6778144/41623682-06e03654-7403-11e8-8fb3-d4edd42276eb.PNG)

**Comment by Kevin-GIS** [comment]
@yapiyapo Can you please share the crash log with us?

On your device, outside of Collector, go to Settings > Privacy > Analytics > Analytics Data. Look for the Collector crash log, per its time stamp. Then select it and use the Share button in the upper right corner to email it to yourself then attach it here.

**Comment by Kevin-GIS** [comment]
Does it crash only with that map, or any map when you attempt to take offline?

**Comment by yapiyapo** [comment]
I only tried it with that map. And it saying, we don't support your file type (Collector crash log) when I tried to attached on this comment section.

**Comment by yapiyapo** [comment]
I changed the file extension to log. 
[accessoryd-2018-04-14-165551.log](https://github.com/doug-m/CollectorAuroraTesting/files/2117128/accessoryd-2018-04-14-165551.log)

**Comment by Kevin-GIS** [comment]
Thanks @yapiyapo 

Can you also share the map with me?

**Comment by niravi** [comment]
logged SF 1008

**Comment by Kevin-GIS** [comment]
This issue has been resolved.
