### ISSUE TITLE
Caching Offline Area

### ISSUE THREAD

**Issue by cskeating** [doug-m/CollectorAuroraTesting#155]
Previous version allowed the ability to change the cache box size
-Now it seems that only a choice of size area (room, building etc.), this makes it hard to get the right size area cached down, either too small or too large. 

### Map and Credentials

* Group Name:
* Map Name:

### Device Information
* Device:
* OS Version:

**Comment by cskeating** [comment]
Also, where can I find how to use pre-planned areas to cache offline maps? I cant seem to find it. This new version mentioned it was available now.

**Comment by doug-m** [comment]
@cskeating for raster basemaps (e.g. imagery) the box is sized automatically.  Sounds like this was discussed in more detail here: https://github.com/doug-m/CollectorAuroraTesting/issues/103

Regarding creating pre-planned offline areas, you'd do that from ArcGIS Online via the web map item.  https://doc.arcgis.com/en/arcgis-online/manage-data/take-maps-offline.htm

**Comment by Kevin-GIS** [comment]
Closing as a duplicate.
