### ISSUE TITLE
Offline area not found, download error

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#158]
### Issue
I am receiving a download error for a specific offline area when attempting to download to my device. "Download Error. Not Found"

### Expected Behavior
n/a

### Map and Credentials

* Group Name: Collector Holistic 8/21
* Map Name: WollyStar_Aurora

### Steps to Reproduce

Map area creation seemed to have froze in ArcGIS Online. I eventually refreshed the page but did not see the area so I moved on instead of recreating the area. Later in Aurora I noticed this offline area was available for download but upon attempting to download I received the error "Download Error. Not Found". It does now appear in ArcGIS Online under manage areas, but I cannot update it. 

### Device Information
* Device: Iphone 6
* OS Version: 11.4.1
![img_0313](https://user-images.githubusercontent.com/15009559/44425553-0a5b1a00-a541-11e8-9c5e-16bec154c424.PNG)

**Comment by miaogeng** [comment]
@colinlawr if you open the area you created, do you see anything created inside the package, something like below? I have seen it empty list before. The empty list state will cause the error message shown on Collector. 

![image](https://user-images.githubusercontent.com/19719166/44425833-e1875480-a541-11e8-9db8-f7a6514a2422.png)

**Comment by colinlawr** [comment]
@miaogeng Yes, it shows an empty list with no updates. I removed it already but reproduced it again if you need any more info from me.

**Comment by jon-esriuk** [comment]
I've mentioned this by email, and I've been asked to log here as well as it looks like I'm seeing the same issue.  I can see the managed offline map areas in ArcGIS Online (screenshot below) but when I look at the details for each area, they don’t contain anything (screenshot further below).  Trying to access either of the prepared offline map areas in Aurora results in a download error (screenshot further below).

Many thanks,

Jon

![01](https://user-images.githubusercontent.com/42581958/44473354-0ce46f00-a628-11e8-845e-e7033aa167d8.png)

![02](https://user-images.githubusercontent.com/42581958/44473375-1241b980-a628-11e8-8a18-0740e8d349a8.png)

![03](https://user-images.githubusercontent.com/42581958/44473398-1a015e00-a628-11e8-8e1c-7d99e5b543a5.png)

**Comment by Kevin-GIS** [comment]
Closing this issue as this behavior has been addressed.

The original issue was likely due to trying to download the area before all of its components were built through AGOL, such as the TPK or the SQLite geodatabase.

Collector now displays 'Generating...' for any preplanned area that is still getting built and prevents it from getting downloaded until its completed. Once all the necessary components of the offline area have been generated, it should be available for download in Collector.
