### ISSUE TITLE
"Invalid map" listed under On Device after removing offline area

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#159]
### Issue
After removing offline area, a listing with that offline area name will appear in under the Recent Items header with a small file size (136kb). Clicking this map will create an "Invalid map" item under the On Device header.

### Expected Behavior
The area should not appear under recent items after it has been removed

### Map and Credentials

* Group Name: Collector Holistic 8/21
* Map Name: WollyStar_Aurora

### Steps to Reproduce
1. Download and open an Offline Area for one of your Web Maps
2. Use the back button to return to the maps list
3. Click the same Web Map to access the Offline Areas
4. Remove the Offline Area and return to the home map list
5. The Map Area that was just removed will appear under Recenter Item header (*sometimes I needed to pull down to refresh the view)
6. Clicking this item will create an Invalid Map item under the On Device header.

"Opening" the map will put you in a perpetual loading screen; must force quit app. 

### Device Information
* Device: iphone 6
* OS Version: 11.4.1
![invalid_map](https://user-images.githubusercontent.com/15009559/44428802-51014200-a54a-11e8-8b50-c3808f7538d0.PNG)

**Comment by Kevin-GIS** [comment]
@colinlawr I cannot reproduce this issue. Could you please share a screen recording of the workflow from your iPhone?

**Comment by colinlawr** [comment]
@Kevin-GIS Here is a recording

[InvalidMap_record.zip](https://github.com/doug-m/CollectorAuroraTesting/files/2308199/InvalidMap_record.zip)

**Comment by Kevin-GIS** [comment]
Thanks for the recording @colinlawr.  This only happens with preplanned offline maps and not adhoc offline maps?  I tested with an adhoc offline map.

**Comment by colinlawr** [comment]
@Kevin-GIS All testing for this was done with preplanned areas. I dont believe I had the same issue with adhoc maps

**Comment by Kevin-GIS** [comment]
This issue has been addressed and resolved.
