### ISSUE TITLE
RE: stream mode when collecting line feature

### ISSUE THREAD

**Issue by DerekLaw** [doug-m/CollectorAuroraTesting#16]
### Issue
I wanted to collect a line feature with stream mode "on", I walked in a straight line - but for some reason, the collected line appears crooked and not straight. Please see picture. Perhaps this was caused by the fact that I may have been on the Esri wifi but after I walked far enough away from the building, my phone switched to my cell plan?

### Expected Behavior
I was expecting to get a straight line, instead of a crooked line.

### Map and Credentials

* Group Name: Aurora Test April 5 
* Map Name: Aurora Map 2 April 5

### Steps to Reproduce
1. Open web map in Collector
2. Start to collect a new line feature, turn on streaming

### Device Information
* Device: iPhone 7
* OS Version: 11.2.6

Observe how the line feature seems crooked

![img_5674](https://user-images.githubusercontent.com/1037228/38383784-3f99dada-38c2-11e8-831e-46d5be7ef07d.PNG)

**Comment by miaogeng** [comment]
It is possible. You can't expect straight line using smartphone location service. Here is a blog: https://www.esri.com/arcgis-blog/products/arcgis-online/field-mobility/smartphones-tablets-and-gps-accuracy/. That is why you need external high accuracy receiver.

**Comment by doug-m** [comment]
As mentioned above, using the internal receiver will utilize additional sources such as WiFi and Cellular towers.  Not much we can do here.
