### ISSUE TITLE
Reloading layers that fail to load due to timeout

### ISSUE THREAD

**Issue by sbatmdc** [doug-m/CollectorAuroraTesting#161]
### Issue
When working with a map that contains a large number of feature layers (120+), the application fails to load all of the layers. The number of layers that are loaded each time varies, but in the latest build there seems to be better performance as nearly 80 layers load before the rest timeout. I've reported this issue before and I just wanted to inform the team the issue is still present but it seems to be an improvement. Additionally, it the latest build I am able to choose to manually reload layers that timed out the first time which is great. However, would it be possible to have an option to reload all of the layers that timed out at once instead of having to go through each layer that failed? Its still pretty time consuming to reload 40 layers individually.

### Device Information
* Device: iPad Air
* OS Version: 11.1.2

**Comment by jeffshaner** [comment]
@sbatmdc it would be great if we can better understand your map composition. We rarely see maps that have more than a few layers in them and I would like to understand why you have over 120? 

How many of those layers are you editing in the field vs are used as reference? For the reference layers are they feature layers because you need to support popups on them? Could they be burned into a VTPK or TPK? All things we would like to understand.

**Comment by sbatmdc** [comment]
@jeffshaner the map we are using contains 121 layers published from a single feature service hosted on our ArcGIS server. The map is used by our field staff to perform an infrastructure asset inventory across all of the conservation areas and lands we manage in the State of Missouri (1,200+ areas, 1,000,000+ acres). All of the feature layers are used for editing in the field and represent potential assets teams may encounter.

Unfortunately, we currently have no way of knowing what types of assets may be located at each specific area, and we need our teams to be able to accurately collect anything the encounter while on site, so we need to include all 121 layers in the map. Due to limited connectivity our teams are using the maps offline and then syncing their edits when they have internet access.

This is a production workflow that we are currently using with the current version of Collector. When I was at ESRI UC, I stopped by the booth and found that the Explorer application also had the same issue of layers not loading.

**Comment by Kevin-GIS** [comment]
Thanks for the feedback @sbatmdc 

Layer timeout issue - Logged SF 948
Overall layer loading behavior - Logged SF 809

**Comment by Kevin-GIS** [comment]
This issue has been addressed. Users will now have the ability to reload groups of layers as oppose to each layer individually.

**Comment by Kevin-GIS** [comment]
The underlying issue for the layer timeout in general, wrt the map above, is still under investigation.

**Comment by Kevin-GIS** [comment]
This issue has been addressed. Closing this issue.

**Comment by sbatmdc** [comment]
I was just wanting to know if there will be an update released for the application where this fix has been implemented? As of the initial release to the App Store 18.1.0, this issue is still present and prohibits us from implementing the new Collector in our production workflows.

**Comment by doug-m** [comment]
This will be released, but not in our next update as the changes are in the underlying ArcGIS Runtime SDK.  Best guess would be end of Q1 2019.
