### ISSUE TITLE
Collector crashes when downloading pre-planned offline area

### ISSUE THREAD

**Issue by asmyrk** [doug-m/CollectorAuroraTesting#162]
### Issue
Using the National Geographic base map.  Created area.  Shows in ArcGIS Online as only being 2.5 MB.  Go to Collector to download.  Download wheel gets all the way around, and then Collector closes.  When I go back in and check, the base map is not downloaded.

I did already have an ad hoc area downloaded.

### Expected Behavior
Download completes as usual

### Map and Credentials
PolesWithLightsInspection
* Group Name: Asset Repair
* Map Name: PolesWithLightsInspection

### Device Information
* Device: iPhone 6
* OS Version: 11.4

**Comment by miaogeng** [comment]
Thanks for reporting. I can reproduce the issue.
