### ISSUE TITLE
No Directional Guidance from Compass When Using GPS Receiver

### ISSUE THREAD

**Issue by azotter** [doug-m/CollectorAuroraTesting#165]
### Issue

No guidance toward point using Compass if using a GPS receiver is used for location.  

### Expected Behavior

I would expect that when a point is selected to navigate to it using Compass, while connected to a high precision GPS receiver (R2), I should still see a line drawing me into the point with the distance updating to reflect that I'm approaching it.  

### Map and Credentials

* Group Name:  GPS
* Map Name:  OH Prioritized FAA Inspections

### Steps to Reproduce
1. Bluetooth connect to GPS receiver
2. Select receiver as "Provider" within "Location" category of Profile settings
3. Open up map (OH Prioritized FAA Inspections)
4. Select a point
5. Select "Compass" to begin navigation

### Device Information
* Device: iPhone7
* OS Version: iOS 11.4.1

**Comment by Kevin-GIS** [comment]
Hi @azotter 

Just for clarification, you're only seeing this issue when using an external receiver? 

If you were to switch back to the integrated receiver > open the map > obtain a fix over WiFi/Cellular > select an existing feature > choose the Compass tool > do you see the line connecting you're GPS location to that feature along with the bearing/distance displayed in the GPS banner?

Can you please attach a screenshot of what your screen looks like while in Compass mode with the external receiver?

**Comment by azotter** [comment]
Hi Kevin,

I actually just tried to reproduce this, and I was unable to do so.  I'm 
not sure what happened, but I just used the R2 again and it give 
directional guidance as I expected.  Thanks for the quick follow-up!

Andrew Zotter
Project Manager | GPS Technology Program
571-243-7381 | azotter@nisource.com

**Comment by Kevin-GIS** [comment]
Thank you for the feedback @azotter 

Glad to hear its working now.

Please let me know if that issue happens again. I will go ahead and close this issue for now.
