### ISSUE TITLE
Only current map visible when switching to offline mode

### ISSUE THREAD

**Issue by kditterline** [doug-m/CollectorAuroraTesting#168]
### Issue
After creating offline areas for two different Collector maps, only the 'current' map is shown once switching my device to airplane mode.

### Expected Behavior
In the current Production version of Collector, all offline maps are available to switch between once device is 'in offline mode'.

### Steps to Reproduce
1. Create offline areas in two maps. 
2. Open a map with offline area to set it as current. 
3. Turn on airplane mode/take phone out of service, notice only current map is available, not every offline map.

### Device Information
* Device: iphone 5s
* OS Version: 11.4

Screenshots of Service/No Service, no service only showing current map with offline area, not both maps.
![4d69face-a70f-441c-86a2-25c0541fdcdf](https://user-images.githubusercontent.com/42583122/44523810-47dab700-a6a9-11e8-9e9e-1493dc3cf306.png)

![2cc4f317-4407-47ca-b556-6e9e4e3a476b](https://user-images.githubusercontent.com/42583122/44523832-5aed8700-a6a9-11e8-8a73-58b4276821a4.png)

**Comment by Kevin-GIS** [comment]
Thanks for the feedback @kditterline 

Issues SF 898 and 730
