### ISSUE TITLE
C25 - Localization of Picklist of zoomlevels not localized

### ISSUE THREAD

**Issue by trichtl** [doug-m/CollectorAuroraTesting#171]
### Issue
Picklist for the zoomlevels are not yet localized, complete other UI is localized (german)

### Expected Behavior
picklist for download area should also be localized - Maybe it's coming later

### Map and Credentials
Every Map

### Steps to Reproduce
Run Collector on German iOS and take a map offline

### Device Information
* Device: iPad Air 2
* OS Version: iOS 11.4.1

**Comment by Kevin-GIS** [comment]
Thanks for the feedback @trichtl 

This will be included with SF 1041

**Comment by trichtl** [comment]
Hi Kevin, good News this is now implemented in Build 2440

**Comment by Kevin-GIS** [comment]
@trichtl thanks for verifying this behavior. It looks good on my end also. Closing this issue.
