### ISSUE TITLE
Offline tile package doesn't contain available levels of detail from base map

### ISSUE THREAD

**Issue by jon-esriuk** [doug-m/CollectorAuroraTesting#174]
### Issue
Offline tile package doesn't contain the available levels of detail from base map

### Expected Behavior
The anticipated behaviour is that for web maps with areas of prepared data to use offline, the tile package would contain the available levels of details from the base map.

Alternatively, could there be an option to specify the level of detail that’s extracted for the tile package?

### Map and Credentials
Publicly available web map at https://arcg.is/WDuOW

### Steps to Reproduce
Create a new area for offline use at an appropriate extent, and allow this to be packaged
Download offline area in Aurora
Zoom in to observe available levels of detail

### Device Information
* Device: iPhone 6S
* OS Version: 11.4.1

Screenshots attached for offline area and available level of detail in Aurora

![manage areas 2018 09 18](https://user-images.githubusercontent.com/42581958/46008821-b8fcf800-c0b5-11e8-8a7e-ad54fe152c83.png)

![img_0228](https://user-images.githubusercontent.com/42581958/46008704-64f21380-c0b5-11e8-9734-84b0656beae0.PNG)

![img_0229](https://user-images.githubusercontent.com/42581958/46008722-73402f80-c0b5-11e8-9f75-f2df7e40fc7c.PNG)

**Comment by miaogeng** [comment]
@jon-esriuk You need to set the level of the details when you create the area. By default, it is `neighborhood` level.

<img src="https://user-images.githubusercontent.com/19719166/46382052-ea4d6900-c65d-11e8-89c5-40f27e2159c0.png" width="40%" height="40%">
