### ISSUE TITLE
C26 - Pointsymbol not displayed as defined in Collector (works in Pro and Online)

### ISSUE THREAD

**Issue by trichtl** [doug-m/CollectorAuroraTesting#175]
Dear Esri-Team,

Software: Collector
Verion  : Build 2440
OS      : iOS 12.0, iPad Air 2

Description:

setup a Point symbology with Arcade Labling (no rotation), displays fine in ArcGIS Pro and also within a Featureservice in 
ArcGIS Online Viewer and also when consuming back in Pro.

When opening that WebMap in Collector, it shows the correct Arcade Labeling, but the point symbol is not real at the size as 
definied.

Attached the data and screendumps to reproduce the problem.

Best regards,

Gerhard "Luigi" Trichtl

[C26.zip](https://github.com/doug-m/CollectorAuroraTesting/files/2439089/C26.zip)

**Comment by Kevin-GIS** [comment]
Thanks for the feedback @trichtl 

The issue here is that renderer for 'Types and Size' uses arcade expressions, which isn't currently supported in Collector. This goes for all arcade based renderers. This is why the symbols display very small. 

Logged Common 1066

**Comment by trichtl** [comment]
Hi @Kevin-GIS in rechecking with Build 2469 I found the real issue - Symbol is set to scale by reference scale, which is not yet supported by runtime - this in on the list for update 100.5 - that's the reason why the Point Symbol didn't Display correctly.

**Comment by Kevin-GIS** [comment]
Thanks for the feedback @trichtl

**Comment by trichtl** [comment]
@Kevin-GIS - just retested - Problem is fixed now - symbolscaling works well
