### ISSUE TITLE
C27 - Feedback UI - functions bold and not bold, middle black instead of white

### ISSUE THREAD

**Issue by trichtl** [doug-m/CollectorAuroraTesting#176]
#
Dear Esri-Team,

Software: Collector (Aurora)
Version : 2440
OS      : iOS 12 - german
Modell  : iPad Air 2

Description:

when you go in the Profile - Info - Feedback - the Send (Senden) on the right is bold and the cancel (Abbrechen) is just in normal style (in brackets the german words in german UI)
In comparisso to other there is always in the left < Profile not bold so I assume the cancel is also not bold.

Also the Collector Feedback is in Black, in the other UI the middle is always white - shouldn't this also white?

Gerhard "Luigi" Trichtl

**Comment by aeveland** [comment]
Thanks. This will be covered in change to light navigation bars.

**Comment by trichtl** [comment]
Verified with Build 2469 now it is consistent within the UI
