### ISSUE TITLE
Arcade expression inconsistently expressing symbol attribute 

### ISSUE THREAD

**Issue by erikjamesmason** [doug-m/CollectorAuroraTesting#180]
### Issue
Arcade expression not “expressing” consistently in Collector aurora. Expression “expresses” once selected then eventually reverts back to static/initial state.  

### Expected Behavior
In this scenario, I have several stations (traffic counters) that are in a collection period of 7 days. I have made an expression in the Change Style (Choose an attribute to show) that changes the size if feature was "checked" that day via use a a "current check" date/time field. If checked on date that matches today's date, the feature symbol expands in size. indicating that it has already been checked.

### Map and Credentials

[https://arcg.is/19bLf4]
(https://arcg.is/19bLf4)
 
 Please if making changes to reproduce issue, leave a comment for easier reversion 

### Steps to Reproduce

Follow link to web map
Select station (preferably one that is in screen shot)
Adjust Date/Time field to today’s date
Symbol should express as an increment in size (completely functioning on AGOL, issue with collector only) 

### Device Information
* Device: iPad 
* OS Version: 11.4.1

![df6b64c9-9595-4c1a-8d06-acacd5a69da4](https://user-images.githubusercontent.com/43789112/46372034-751a6d80-c636-11e8-8cc0-8026cbbfcac1.png)
![523dc65f-dff6-442c-89da-88cfb7894dc6](https://user-images.githubusercontent.com/43789112/46372035-751a6d80-c636-11e8-9146-e88cca2a2975.png)
![c6698836-36a8-4384-9e15-8df520b4e439](https://user-images.githubusercontent.com/43789112/46372036-751a6d80-c636-11e8-9210-c8072ed70c54.png)

I also have a screen recording if necessary

**Comment by miaogeng** [comment]
@erikjamesmason in current Aurora, we only support arcade expression for label and read only popup. Arcade expression for symbology doesn't support yet. 

Note: common 1066

**Comment by erikjamesmason** [comment]
@miaogeng I've read that, but I have been using the same/similar expression in my attribute for symbology for a few months now and it's worked (fairly) consistently. Not that I doubt what you stated, but maybe we should re-categorize this as an enhancement suggestion? For working in offline rural areas (A lot of our field work is in rural Alaska), this is a great way to keep track of which stations have been checked already. It is easier than one would think to forget or pass a station after a 12-14 hour day.

**Comment by erikjamesmason** [comment]
@miaogeng sorry, just saw that you already relabeled. Thanks!
