### ISSUE TITLE
Connection to Trimble R2

### ISSUE THREAD

**Issue by akoostra** [doug-m/CollectorAuroraTesting#181]
### Issue
GPS is around 3 feet off compared to the base map it appears Aurora does not see the location profile.  Aurora also seems to kick Trimble's GNSS status app back to location services from the R2 unit do not even know if that is technically possible.

### Expected Behavior
Current version of Collector works on the same iOS device and R2 unit.

### Map and Credentials

* Group Name:
* Map Name:

### Device Information
* Device: iPhone XS
* OS Version: Latest

**Comment by doug-m** [comment]
@akoostra FYI you should not use the GNSS Status app in conjunction with Aurora.  Unlike Collector, use of Trimble receivers with Aurora do not require the GNSS Status app (it does not need to be installed).

**Comment by akoostra** [comment]
How do you provide base station settings for corrections?  In the R2 unit?

**Comment by doug-m** [comment]
@akoostra you'd do that within Aurora - tap the `i` for the Trimble R2 in the Location Provider, and define your correction source.

**Comment by akoostra** [comment]
Ok guess I am missing something when I tap the i only option I get is antenna height.

**Comment by doug-m** [comment]
@akoostra can you verify you're using Build 2440?

**Comment by akoostra** [comment]
Having trouble finding the 2440 Build can you point me in the right direction?

**Comment by doug-m** [comment]
@akoostra yep, can you install 2440 and retry your test?

**Comment by akoostra** [comment]
I can not locate 2440 anywhere to install.

**Comment by psp2k** [comment]
Will assume this is related only to not having proper build. Let me know if further input from Trimble is needed.

**Comment by akoostra** [comment]
Ok let me know if I can download the latest build my TestFlight isn’t showing it. Will test using integrated location until then.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by doug-m** [comment]
@akoostra re-added you in hopes that resolves the problem.  Let me know if 2440 shows up in TestFlight for you.

**Comment by akoostra** [comment]
Yes that worked. Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by doug-m** [comment]
Excellent - glad you have the right build now to do some testing.  Look forward to your testing results.

**Comment by akoostra** [comment]
Connection issues I had were resolved with build 2440.  It does seem the profile keeps reverting to default and the profile i create disappears if I open and close Collector which is kind of a hassle.

**Comment by miaogeng** [comment]
@akoostra I have seen this issue in this holistic build. We will look into it. BTW, with the profile configured, do you still see the shift?

**Comment by akoostra** [comment]
No shift with the correct profile.

Andy Koostra |  akoostra@tngeo.com<mailto:akoostra@tngeo.com>
True North Geographic Technologies

**Comment by miaogeng** [comment]
This should be addressed in next beta build.
