### ISSUE TITLE
Default basemap does not load after switching basemaps

### ISSUE THREAD

**Issue by amilanetti** [doug-m/CollectorAuroraTesting#183]
### Issue
After switching the basemap using the Basemap selector the Default basemap will no longer load. 

### Expected Behavior
When clicking on 'Default' it would be expected that the basemap would switch back to the original basemap used in the web map. 

### Map and Credentials
* Group Name: Alex - Holistic Testing
* Map Name: Holistic Testing - World Basemap v2 Vector

### Steps to Reproduce
A. Organization Settings
Basemap Gallery
Set to "Esri Default"
Uncheck "Use Esri vector basemaps in supported ArcGIS apps"

B. Web Map
1. Create a web map with an editable layer and using the World Basemap v2 (vector basemap)
2. Open this map online in Aurora.
3. Click the overflow button -> Basemap
4. Select a different basemap and this should load
5. Try to select 'Default' -> the basemap will disappear and the Default basemap will not load leaving a blank background.
6. Reloading the map allows the original basemap to show again.

I think the issue may be that the basemap used to create the web map is not part of the Organization's basemap gallery. In ArcGIS Online I would not have a way to go back to this basemap using the basemap selector as it is not included. However, since the Default button is there in Aurora you expect the original basemap to load again.
  
### Device Information
* Device: iPad Air 2
* OS Version: iOS 12.0

**Comment by Kevin-GIS** [comment]
Thanks for the feedback @amilanetti 

Logged SF 985

**Comment by Kevin-GIS** [comment]
This issue has been addressed. Closing this issue.
