### ISSUE TITLE
Insufficient character space for Text field type under pending edits. 

### ISSUE THREAD

**Issue by allanSV27** [doug-m/CollectorAuroraTesting#187]
### Issue
When filling in a Text type field, there is not enough character space for the Pending Edits section when a significantly long text is used.  Please see screenshot below.

### Expected Behavior
The character limit is set to 255. The pending edits section should allow for this many characters so that it does not overlap. The attribute table view appears to accommodate the long text just fine.

### Steps to Reproduce
1. Create an offline enabled map with a feature service. For this issue, a hosted feature service containing points was used.
2. Make sure the hosted feature service uses at least one text field 
3. Perform an attribute edit, and make sure to use a significantly long text name ~100 characters long 
4. Select the Submit option.
5. Select the Sync option to view the Pending Edits and notice how the entries overlap and do not line up with the lines. 

### Device Information
* Device: iPhone 6
* OS Version: 12

![texterror](https://user-images.githubusercontent.com/43788371/46379347-60989e00-c653-11e8-85f7-54aee9169c45.jpg)

**Comment by Kevin-GIS** [comment]
This issue has been addressed. Closing this issue.
