### ISSUE TITLE
Map areas corrupt and/or fail to reflect changes to settings in feature services

### ISSUE THREAD

**Issue by wbrewer-calfire** [doug-m/CollectorAuroraTesting#188]
### Issue
Pre-defined areas for offline maps can corrupt and/or won't honor changes to the settings of underlying feature services. For example (1), a feature service that has editing disabled will still receive edits if editing was enabled when the pre-defined map area was created. (2) Changing the settings of  a feature service (making it not syncable and then re-enabling sync) will cause the map area to fail to download.

### Expected Behavior
Settings for pre-defined areas should reflect the current settings in the feature services, not just the settings of the feature services present at the time of the creation of the pre-defined area.

### Map and Credentials

* Group Name: 'Test Group'
* Map Name: 'prefire_related_table_map_1002'

### Steps to Reproduce
1) Publish a map with editable and syncable feature service. 2) Create map area. 3) Change settings of feature service (make un-editable or non-syncable). 

### Device Information
* Device: iPhone 8
* OS Version: iOS 11.4.1

![not_found](https://user-images.githubusercontent.com/43791109/46380252-7d82a080-c656-11e8-996e-b7141213bc00.png)
![unable_to_create_replica](https://user-images.githubusercontent.com/43791109/46380264-82dfeb00-c656-11e8-8b20-f5755e0e80b8.png)

**Comment by miaogeng** [comment]
@wbrewer-calfire have you tried to use "recreate" to see if the setting is refresh this way?

<img src="https://user-images.githubusercontent.com/19719166/46381786-9e4df480-c65c-11e8-9ea3-612f31a09f77.png" width="40%" height="40%">

**Comment by wbrewer-calfire** [comment]
That worked. It's a good process, but I will have to do that for each map area instead of doing it once on the feature service if I were to change its settings. Thanks for the help!

**Comment by miaogeng** [comment]
I will bring this feedback to the team. Currently we consider it as design.
