### ISSUE TITLE
Offline Areas seem to package indefinitely in ArcGIS Online

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#189]
### Issue
When creating a new offline area in ArcGIS Online through the Manage Areas screen, I see that an area is created and now listed under Map Areas. After several hours passed and clicking on this area in the same screen to reveal more details, there is an indicator that this area is still "packaging". We also noticed there is only the map tile icon listed here. 

![offline_area](https://user-images.githubusercontent.com/15009559/46382266-32b95680-c65f-11e8-8927-3eeb0b8429ad.png)
The offline area is listed in Collector under offline areas, but gives a download error "not found" when attempting to download. It's a small area (a few city blocks) and down to the small building level.

### Expected Behavior
I would expect the offline area to generate successfully and within a few minutes. There were existing offline areas for this map that were created a few weeks ago successfully. 

### Map and Credentials

* Group Name: Collector Holistic 10/2
* Map Name: WollyStar_Aurora_offline

### Steps to Reproduce
Please use the above map to access the Manage Areas screen in the Web Map settings. 

### Device Information
* Device: iphone 6
* OS Version: iOS 11.4.1

**Comment by wbrewer-calfire** [comment]
I have had the same issue. When it seems the map area is taking forever to package I will refresh the url and the status will change. Might try this, but if the map area isn't downloading in Aurora there may be a bigger issue.

**Comment by Kevin-GIS** [comment]
Closing this issue as no longer being reproducible.

Recent testing in ArcGIS Online hasn't reproduced this behavior, as the package generation process has been working successfully for multiple maps and areas.
