### ISSUE TITLE
RE: attachment questions

### ISSUE THREAD

**Issue by DerekLaw** [doug-m/CollectorAuroraTesting#19]
### Issue
Not an issue, some questions:

Q: What is the "limit" for an audio attachment? How long can the recording be? I ask because in Survey123 for ArcGIS it is 2 mins, I expect customers will ask this for comparison purposes.

Q2: Is there a "limit" for video attachments? If so, what is it?

Will this info be documented?

Love that you support these (plus images) and love that you can rename all the attachments. Awesome.

### Expected Behavior
N/A

### Map and Credentials
N/A

### Steps to Reproduce
N/A

### Device Information
* Device: iPhone 7
* OS Version: 11.2.6

**Comment by bethanyw** [comment]
Completely agree- especially due to the limits set by Survey123

**Comment by miaogeng** [comment]
We are aware of this limitation. We will either address it or document the limitation.  
Note: sf 782

**Comment by kyliedonia** [comment]
Included notes in the in-progress Aurora doc.

**Comment by caro7202** [comment]
We now have support for multi-part uploads. There should not be any limit when uploading.
