### ISSUE TITLE
Unable to "Sign In with ArcGIS Enterprise" account

### ISSUE THREAD

**Issue by willylynch** [doug-m/CollectorAuroraTesting#190]
### Issue

While on VPN and connected to our network, I am unable to "Sign In with ArcGIS Enterprise" account
### Expected Behavior

click on Sign In with ArcGIS Enterprise, enter Portal URL and then be prompted for credentials.  The prompt for credentials never appears. Message "Unable to Connect to Portal" Credentials Required.
### Map and Credentials

* Group Name:
* Map Name:

### Device Information
* Device: iPhone 6
* OS Version: iOS12

**Comment by willylynch** [comment]
No problem signing into ArcGIS Online. Just our Enterprise Portals. I tried several.  All gave same error message.

**Comment by caro7202** [comment]
Addressed in SF 1186

**Comment by Kevin-GIS** [comment]
This issue has been addressed. Closing this issue.
