### ISSUE TITLE
Able to create map areas with same name

### ISSUE THREAD

**Issue by amilanetti** [doug-m/CollectorAuroraTesting#192]
### Issue
I was able to create different map areas with the same name when creating one through the "Add Offline Area" options in Aurora and the other through "Manage Areas" in ArcGIS Online.

### Expected Behavior
I would expect that you would not want a user to be able to have more than one map area on their device with the same names for the same map.

### Map and Credentials
* Group Name: Alex - Holistic Testing
* Map Name: Holistic Testing - Offline

### Steps to Reproduce

1. Area 1
a. Add Offline Area in Aurora named "Area 1"
b. Manage Areas in ArcGIS Online -> Create new area
i. I first tried to create an area named "Holistic Testing - Offline_Map - Area 1" but I received the error "Title must be unique". 
ii. I then tried to create an area named "Area 1" and it let me create this. 
-- This resulted in two map areas with the same name in Aurora. 

2. Area 2 
a. ArcGIS Online -> Created area named "Holistic Testing - Offline_Map - Area 2"
b. Aurora -> Created area named "Area 2" 
-- These show as their respective names in Aurora.

3. Area 3
a. ArcGIS Online -> Created area named "Area 3"
b. Aurora -> Created area named "Area 3" 
-- This resulted in two map areas with the same name in Aurora. 

### Device Information
* Device: iPad Air 2
* OS Version: iOS 12.0

**Comment by aeveland** [comment]
Thanks for the feedback. Logged in SF 1246

**Comment by Kevin-GIS** [comment]
This issue has been addressed. Closing this issue.
