### ISSUE TITLE
Documentation on accessing offline backups needs to be updated for ArcGIS Pro

### ISSUE THREAD

**Issue by mschenker** [doug-m/CollectorAuroraTesting#193]
### Issue
I just tested accessing offline backups from Collector Aurora.
The workflow as described in [https://support.esri.com/en/technical-article/000012460](https://support.esri.com/en/technical-article/000012460) still works.
It would however also be helpful to mention on this page that the .geodatabase file can be read directly from ArcGIS Pro, no GP-Tool is necessary.

**Comment by kyliedonia** [comment]
Thanks @mschenker - We'll get that updated.

cc 1143

**Comment by Kevin-GIS** [comment]
This issue has been addressed. Closing this issue.
