### ISSUE TITLE
Offline: fail to use ad-hoc to take map offline

### ISSUE THREAD

**Issue by msmith12345** [doug-m/CollectorAuroraTesting#195]
### Issue
Collector stops working (hangs up) when working with Ad Hoc map.  Is the ad hoc (offline map) going away?  We would like the ability to define our own work area which currently exists in the Collector Classic. 

### Expected Behavior
The ability to define the offline work area and not use the defined level of detail.

### Map and Credentials
* Group Name: OSFM DSpace Staging
* Map Name: PREFIRE2019_V2_1_MAP

### Steps to Reproduce

1. Open Map
2. Click Add Offline Area
3. Zoom in or out 
4. Collector stopped working - not able to click on any of the buttons - must restart the application

### Device Information
* Device: iPAD
* OS Version: iOS 11.4.1 (15G77)

**Comment by miaogeng** [comment]
@msmith12345 I can't reproduce the issue. BTW, PREFIRE2019_V2_1_MAP is not the map for offline. I use PREFIRE2019_V2_1_MAP_OFFLINE to test.  Can you try again and record the screen using https://support.apple.com/en-us/HT207935?

**Comment by msmith12345** [comment]
Here is the screenshot... I don't think you can tell the screen is locked... but I cannot tap on any of the buttons...I have tried different maps and I get the same results...    The map I used for this screenshot is called Prefire2019_V2_Subtypes ... it is located in the OSFM DSpace Staging


The steps:


  1.  Tap the ... dots next to the map title
  2.  Tap Add Offline Area
  3.  Start zooming in and out... the screen freezes.


I hope this helps...


[cid:574669d0-cf7e-478f-86a5-3d0dcb300b33]

Mickie Smith
California Department of Forestry and Fire Protection
OSFM
(916) 568-2924
________________________________

**Comment by Kevin-GIS** [comment]
Hi @msmith12345 

When you installed this holistic build, did you install on top of an existing build of Aurora, or was this a fresh install?

Can you still reproduce this issue?

Thanks

**Comment by Kevin-GIS** [comment]
Thanks for the feedback @msmith12345 

When you installed this build of Collector, was there already an existing version on the device that was just upgraded to this new version? Or was this a fresh/new install of this app on this device?

If you were to reinstall the app, can you reproduce the issue?

Thanks

**Comment by doug-m** [comment]
Excellent @msmith12345 glad to hear it, and thanks for following up!

**Comment by Kevin-GIS** [comment]
The underlying issue has been addressed. 

The original issue was due to having Logging enabled in the settings when defining the offline area. Disabling logging was the workaround. Reinstalling the app also disabled logging, which is why that worked.
