### ISSUE TITLE
Map areas created from Aurora or ArcGIS Online have labels even if labels are disabled on the Web Map

### ISSUE THREAD

**Issue by xavierjunod** [doug-m/CollectorAuroraTesting#198]
### Issue
Map areas created from Aurora or ArcGIS Online have labels even if labels are disabled on the Web Map. 
The Web Map had labels enabled, I disabled them and saved the map. The Manage Areas map in ArcGIS Online still shows the labels.  In Aurora the "mini-map" to define the work area also shows labels.

### Expected Behavior
The Map Area should reflect the settings of the Web Map.  When labels are disabled on the Web Map, they should not appear in the Map Area. 

### Map and Credentials

* Group Name: Holistic_testing
* Map Name: Collector_testmap-NoLabels

### Steps to Reproduce

Create a Map area for this map from ArcGIS Online or Aurora.  Notice that the labels are present even if they are disabled in the Collector_testmap-NoLabels Web Map. 

I was able to reproduce with other hosted feature service and Web Maps

### Device Information
* Device: iPad pro A1674
* OS Version: 11

**Comment by Kevin-GIS** [comment]
This issue has been addressed and should be available in the next app update.

Closing this issue.
