### ISSUE TITLE
Configure Maps in AGOL

### ISSUE THREAD

**Issue by msmith12345** [doug-m/CollectorAuroraTesting#199]
### Issue
When you configure the date field to show the date without the time, the collector displays the date correctly, but when viewing it in AGOL table view, the date shows the time.  

The related table shows the date in the table view without the time but when you click on the field it showed the time  

### Expected Behavior
AGOL should not show the time if the map is configured to only show the date.

### Map and Credentials

* Group Name: OSFM DSpace Staging
* Map Name: PREFIRE2019_V2_1_Map

### Steps to Reproduce
Access the table view in AGOL

### Device Information
* Device:  n/a
* OS Version: Windows

![image](https://user-images.githubusercontent.com/43820465/46430119-fdfbdc80-c6fc-11e8-9cc1-7ae454e7750f.png)

![image](https://user-images.githubusercontent.com/43820465/46430126-03592700-c6fd-11e8-9be5-9b915055689c.png)

**Comment by Kevin-GIS** [comment]
Thanks for the feedback @msmith12345

This issue is related to AGOL and not specifically to Collector. I've shared this feedback with the AGOL team. I will go ahead and close this issue.
