### ISSUE TITLE
Sliding attribute panel when collecting features moves target location for collection point in map

### ISSUE THREAD

**Issue by r-ruval** [doug-m/CollectorAuroraTesting#2]
### Issue
When copying or collecting a feature, sliding the attribute panel all the way down moves the target location of a point feature.

### Expected Behavior
Point location on the map should not change if the user is moving attribute panel. Potential to cause inaccurate positioning of point.

### Map and Credentials
Reproducible with any hosted feature layer. "Field Interviews" template was used in testing.
![img_3572](https://user-images.githubusercontent.com/38108580/38380092-9a743938-38b7-11e8-95dc-b341d00d318e.PNG)
![img_3573](https://user-images.githubusercontent.com/38108580/38380093-9a922c18-38b7-11e8-8c55-86b7d7897468.PNG)

### Steps to Reproduce

1. Open map and select a feature > Copy feature 
2. Pan around map to location where point should be placed
3. If user were to update an attribute before clicking on "Update Point", moving the attribute panel all the way down will also move the location of the point from step 2.

### Device Information
* Device: Iphone 8 Plus
* OS Version: 11.2.6

*Screen shots attached

**Comment by colinlawr** [comment]
To add on to this issue:

When using an iPad and rotating between landscape and portrait view, the crosshair will move locations slightly. This only occurs when moving the cross off your current GPS location (manually placing point).

**Comment by Shoumith** [comment]
Notices the same behavior on iPhone 6s. Not sure if sliding the panel moves the point cross hair or the map itself. 

- Shoumith

**Comment by colinlawr** [comment]
This is a similar issue so I am adding it here. When editing an existing point on an iPad in portrait view:

Click Edit and the side panel will close and open the form collection window from the bottom. This moves the cross hairs and can lead to confusion when updating. This has been touched on in other holistic events, but I feel users may be drawn to click "Update Point" after modifying their attributes; inadvertently moving their existing point. 

Either the crosshair shouldnt move from the existing location (unless physically moved) or the wording/location of the "update point" button should be changed.

**Comment by Kevin-GIS** [comment]
This issue has been addressed and is no longer reproducible.
