### ISSUE TITLE
Unable to collect data in offline map - the "+" button is missing

### ISSUE THREAD

**Issue by xavierjunod** [doug-m/CollectorAuroraTesting#206]
### Issue
Unable to collect data in offline map - the "+" button is missing in all offline maps when Wifi is turned off and Collector is rebooted.

The layers are still visible, only the "+" button is missing. 
There were 3 instances during testing where the layers were also missing (not showing up and the layer list was empty), but I have not been able to replicate it consistently. Reconnecting to the internet made the layer appear right away. 

### Expected Behavior

Collecting data should not need to access the internet when  using offline data.  

### Map and Credentials
This issue is not data specific

### Steps to Reproduce

1.  open an offline map area when connected to Wifi
2. Turn Wifi OFF
3. Shut down collector
4. Launch Collector --> it opens the previous map by default
5.  notice that the "+" button to collect data is missing in the map as well as in all offline map areas 
See screenshot: https://www.screencast.com/t/lCHKKtfb0BmD
Solution: reconnect to the internet via wifi or data and reboot collector.  

### Device Information
* Device: iPad Air 2 on iOS12 & iPad Pro on iOS 11

* OS Version:

**Comment by Kevin-GIS** [comment]
Thanks for the feedback @xavierjunod 

Logged SF 1242

**Comment by Kevin-GIS** [comment]
This issue has been addressed. Closing this issue.
