### ISSUE TITLE
C28 - coordinate units the only once which are not tranlated

### ISSUE THREAD

**Issue by trichtl** [doug-m/CollectorAuroraTesting#208]
Dear Esri-Team,

Software: Collector
Verion  : Build 2469
OS      : iOS 12.1, iPad Air 2

Description:

within the profile we could configure the units - all is correctly translated to german - excpet the units for the coordinates, those are still in english.
To be consistent they should be in german as well.

See the attached screenshots.

Best regards,

Gerhard "Luigi" Trichtl
[bug.docx](https://github.com/doug-m/CollectorAuroraTesting/files/2544385/bug.docx)
[bug.txt](https://github.com/doug-m/CollectorAuroraTesting/files/2544386/bug.txt)

**Comment by Kevin-GIS** [comment]
Thanks for the feedback @trichtl 

Sharing this information with the team.

**Comment by Kevin-GIS** [comment]
Logged SF 1336

**Comment by doug-m** [comment]
@trichtl this was addressed in 18.1.0.
