### ISSUE TITLE
C29 - Some terms are not in german yet

### ISSUE THREAD

**Issue by trichtl** [doug-m/CollectorAuroraTesting#209]
Dear Esri-Team,

Software: Collector
Verion  : Build 2469
OS      : iOS 12.1, iPad Air 2

Description:

as we got close to release I still see some terms in english in some UI's - attached some location I found

See the attached screenshots.

Best regards,

Gerhard "Luigi" Trichtl
[bug.docx](https://github.com/doug-m/CollectorAuroraTesting/files/2544421/bug.docx)
[bug.txt](https://github.com/doug-m/CollectorAuroraTesting/files/2544422/bug.txt)

**Comment by Kevin-GIS** [comment]
Thanks @trichtl I will add those to the list.

**Comment by Kevin-GIS** [comment]
Logged SF 1336

**Comment by Kevin-GIS** [comment]
This issue has been addressed. Closing this issue.
