### ISSUE TITLE
Opening the app directly opens the map instead of the map list

### ISSUE THREAD

**Issue by Shoumith** [doug-m/CollectorAuroraTesting#21]
### Issue
When the app is closed and reopened, the app directly opens the map that was last used rather than opening the map list

### Expected Behavior
Expected the map to open the map list 

### Map and Credentials

* Group Name:
* Map Name:

### Steps to Reproduce
- Open a map in Collector from the list of layers
- Close the app, either directly or after you go back to the layer list
- Relaunch the app again, this opens the map directly instead of the map list

### Device Information
* Device: iPhone 6s
* OS Version: iOS 11.x

**Comment by miaogeng** [comment]
@Shoumith when you get a chance, can you explain why you would like to see the map list first?

**Comment by doug-m** [comment]
This behavior is by design.  Many users work with a single map for several days, this is an optimization to better support this reality.
