### ISSUE TITLE
Add to My Places Extent

### ISSUE THREAD

**Issue by sanderson2146** [doug-m/CollectorAuroraTesting#212]
### Issue
When I click add to my places after giving it a name the map centers on a spot near the south pole.

### Expected Behavior
The map should center on the place you just added or the original map extent.

### Map and Credentials

* Group Name: Collector Holistic Testing
* Map Name: AED Test Map

### Steps to Reproduce
1. select a point or a place on the map. 
2. click Add to my Places
3. give the place a name and click okay
4. look at the map

### Device Information
* Device: Android
* OS Version: 7.0

**Comment by Kevin-GIS** [comment]
This issue appears similar to AF 320

**Comment by Kevin-GIS** [comment]
This issue has been addressed and is no longer reproducible. 

Closing this one out.
