### ISSUE TITLE
Unable to take map off-line

### ISSUE THREAD

**Issue by Parks818** [doug-m/CollectorAuroraTesting#214]
### Map and Credentials

* Group Name:
* Map Name:

### Device Information
* Device: Galaxy S9+
* OS Version: Android version 9

**Comment by miaogeng** [comment]
@Parks818 can you share the map to a group and invite the Collector4ArcGIS user to the group so we can review?

**Comment by Parks818** [comment]
@miaogeng invited you to a group I created for this test. Is it because we use ArCGIS On-line and not ArcGIS Enterprise.  Reason I ask is because this map works fine taking areas off-line with the new Aurora Collector for IOS.

**Comment by Parks818** [comment]
I just checked the map in Aurora Collector for IOS. It works fine and allows you to add an offline area.
So odd that  option does not appear on Aurora Collector for Android.

**Comment by kyliedonia** [comment]
The "add offline area" option within the map creates an on-demand offline map area, which isn't supported in this build. This build only supports the preplanned offline map areas defined as part of authoring the web map.

**Comment by Parks818** [comment]
I see. Makes sense now.
