### ISSUE TITLE
Unable to Edit Polygons in One Map

### ISSUE THREAD

**Issue by sanderson2146** [doug-m/CollectorAuroraTesting#215]
### Issue
When opening a feature and then clicking the pencil icon the feature details go away but no editing dialogue comes up.

### Expected Behavior
The edit dialogue should appear.

### Map and Credentials
This is a client portal at 10.6. Happy to show behavior but can't share/create credentials.

### Steps to Reproduce
1. open the map.
2. click on a feature and then click on the pencil icon
3. nothing happens.
4. now unable to select any other features, sometimes crashes

### Device Information
* Device: Android Samsung S6
* OS Version: 7

**Comment by Kevin-GIS** [comment]
Marking this issue as closed for the time being, as we don't have a reproducible environment to test this issue. 

Will reopen if this is still an issue.
