### ISSUE TITLE
Unable to Create Point Offline Outside Map Area

### ISSUE THREAD

**Issue by sanderson2146** [doug-m/CollectorAuroraTesting#216]
### Issue
When trying to create a point outside of an offline area I get an error message.

### Expected Behavior
I thought you used to be able to create points outside of the downloaded map area. If this is expected behavior it's decently concerning from a workflow perspective. If someone drives outside of their map area and finds something they won't be able to record it even if they are connected.

### Map and Credentials

* Group Name: Collector Holistic Testing
* Map Name: Damage Assessment

### Steps to Reproduce
1. download map area
2. try to create a point outside the basemap area
3. get error message

### Device Information
* Device: Android Samsung S6
* OS Version: 7

![Screenshot_20190313-155843 (1)](https://user-images.githubusercontent.com/29313687/54320551-964e9500-45aa-11e9-82bd-fc30e0966a4b.png)

**Comment by miaogeng** [comment]
In Collector classic we don't support create points outside of the downloaded map area either. We consider this as design.
