### ISSUE TITLE
Cannot capture GPS metadata from internal device's GPS

### ISSUE THREAD

**Issue by dheerabhat** [doug-m/CollectorAuroraTesting#218]
### Issue
Cannot capture GPS metadata from internal device's GPS 

### Expected Behavior
Cannot capture GPS metadata from internal device's GPS when using Collector (Aurora) but can collect if using Collector Classic

### Map and Credentials

* Group Name:
* Map Name:
Test with ArcGIS Enterprise 10.6.1

### Device Information
* Device:  CHC LT600T
* OS Version:  5.1

![CollectorClassic](https://user-images.githubusercontent.com/23333720/54357225-36cab500-4690-11e9-9882-7b2ded2d70d6.jpg)
![CollectorAurora](https://user-images.githubusercontent.com/23333720/54357236-3af6d280-4690-11e9-9227-6cb3349be031.jpg)

**Comment by Kevin-GIS** [comment]
Hi @dheerabhat thank you for the feedback, this holistic build doesn't currently have support for the GNSS Metadata fields. Those will be coming later in another beta release.

**Comment by Kevin-GIS** [comment]
This issue has been addressed when receiving locations through NMEA with the Integrated Receiver. This should be available in the next beta release.

Closing this issue out.
