### ISSUE TITLE
Application crashes when modifying the antenna height 

### ISSUE THREAD

**Issue by MattJBallard** [doug-m/CollectorAuroraTesting#219]
### Issue
When I attempt to modify the antenna height, Collector crashes

### Expected Behavior
I should be able to modify the antenna height without the application crashing

### Map and Credentials
Not related to a specific map
* Group Name:
* Map Name:

### Steps to Reproduce
Connect to GNSS device (Eos Arrow Gold)
Attempt to modify the antenna height
Application Crashes

### Device Information
* Device: Pixel 2XL
* OS Version: Android 9

Not sure where to find the crash logs, but I am happy to provide them if I find them.

**Comment by Kevin-GIS** [comment]
Thanks for reporting this issue @MattJBallard 

Logged AF 644

**Comment by caro7202** [comment]
Issue has been fixed. It will be available in the next Beta update.
