### ISSUE TITLE
Sync Error: The operation couldn't be completed

### ISSUE THREAD

**Issue by claire-m-h** [doug-m/CollectorAuroraTesting#23]
### Issue
Received error when syncing offline edits from Web Map with Vector Tile Basemap

### Expected Behavior
Expect the Web Map to sync properly

### Map and Credentials
* Group Name: April 5th: Collector Testing (Support)
* Map Name: Vector Tile Basemap- Offline

### Steps to Reproduce

- Edited map offline (1 polygon feature with 11 photos, 2 audio recordings, 1 line feature with no attachements)
-Sync edits
-Error: "Sync Error: the operation couldn't be completed. (com.esri.arcgis.runtime.services.error error 498)"

### Device Information
* Device: iPhone 8
* OS Version: iOS 11.2.6

![syncerror](https://user-images.githubusercontent.com/38106372/38384702-b770463c-38c4-11e8-9e87-4af8f349be1c.PNG)

**Comment by miaogeng** [comment]
Li will try to reproduce.

**Comment by Kevin-GIS** [comment]
@li2504 were you able to reproduce this issue?

**Comment by Kevin-GIS** [comment]
Closing as not reproducible.
