### ISSUE TITLE
Issue with tpk using custom scheme for offline use in previous portal versions (prior to 10.7)

### ISSUE THREAD

**Issue by robelogb** [doug-m/CollectorAuroraTesting#244]
### Issue

Previous versions of portal  (prior to 10.7) don't have the option to download sideloaded tpk files for offline map as "Device will use a tile package it already has" is not available  and becomes problematic when switching to tpk in basemap switcher in offline map for files that using custom scheme and coordinate system
### Map and Credentials

* Group Name:
* Map Name:
*This is internal (one premise) portal for ArcGIS
### Steps to Reproduce
-side load  tpk to a mobile (tpk using custom scheme and coordinate system)
-open collector and download map along with Esri basemap ( as the option to specify "Device will use a tile package it already has" is not available)
-open map on device and click three dots to open "Basemap"
-here you will see the tpk and click to switch. It will give an error " The spatial reference is not compatible with the map". 

### Device Information
* Device: I phone xs
* OS Version: 13.2

**Comment by miaogeng** [comment]
@robelogb The reason why it shows the error  "The spatial reference is not compatible with the map" is that the existing Esri basemap doesn't have the same spatial reference as tpk. At offline mode, we don't allow to switch basemap with different spatial reference. Have you consider using hosted tile layer at ArcGIS Enterprise (https://enterprise.arcgis.com/en/portal/10.5/use/manage-hosted-tile-layers.htm) or cached map service as a workaround?

**Comment by robelogb** [comment]
@miaogeng 

Thanks. Yes, I understand because of the Esri basemap used different scheme/coordinate system. I see those as work around. I was just exploring the option to use tpk instead and seems like that won't be possible.

**Comment by miaogeng** [comment]
Currently this is a limitation. You will need to update the portal to leverage that capability.
