### ISSUE TITLE
Allow snapping for first edit vertex

### ISSUE THREAD

**Issue by JessicaMcCann** [doug-m/CollectorAuroraTesting#249]
### Issue
Allow snapping in crosshair of first vertex edit.

### Expected Behavior
Have the opportunity to use snapping before first vertex is dropped (for polygon)

### Map and Credentials

* Group Name:
* Map Name:

### Steps to Reproduce
1-Click on the plus sign to add a new feature
2-Move the crosshair (snapping is not yet enabled)
3-Choose your feature template
4-First vertex gets put it where the crosshair was (no snapping involve)
5-To move first vertex using snapping, click on the ellipsis ... and choose "update selected point"
https://www.screencast.com/t/246wX5J6

### Device Information
* Device: Iphone X
* OS Version: iOS 13.2.3

**Comment by miaogeng** [comment]
@JessicaMcCann In the coming beta, you can use snapping at the template selection screen. After picking template, the vertex is kept.

**Comment by JessicaMcCann** [comment]
Thanks!
