### ISSUE TITLE
Update from Portal (server) are not shown in offline map once synced

### ISSUE THREAD

**Issue by robelogb** [doug-m/CollectorAuroraTesting#254]
### Map and Credentials

* Group Name:
* Map Name:

### Steps to Reproduce
-download map for offline ( webmap settings has "Features"  for "editable layers" checked for what to retrieved from server)
-go to map viewer in portal and make edit
-go to device and sync the offline map
-edits made in map viewer is not shown on local mobile device

*tested in 10.6.1 ( haven't tested in 10.7 or latest version) and used registered database( not hosted). seem to be the with the current version of collector as well.
### Device Information
* Device:
* OS Version:

**Comment by miaogeng** [comment]
@robelogb do you register data as version? If it is versioned data, map viewer is editing default version while offline map at Collector is using child version. You need to reconcile and post at the backend and sync at Collecor to see the change.

**Comment by robelogb** [comment]
@miaogeng 

Yes, it is versioned. Thanks!

**Comment by miaogeng** [comment]
Thanks for confirmation.
