### ISSUE TITLE
C13 - Download Map with Vector Tile Serivces (local projection) doesn't start

### ISSUE THREAD

**Issue by trichtl** [doug-m/CollectorAuroraTesting#26]
### Issue
Collector when using local projection with VectorTiles Basemap doesn't download

Software: Collector
Version : Build 2203
OS      : iPad, iOS 11.2.6

* Publish Basemap-Map as VTPK to Online - and enable also download capabilities
* Publish Map as Featureservice to Online with sync enabled
* Create in MapViewer a Map with it and save it
* Open the Map in Collector and zoom to layer - works
* Now take Map offline - Download Area button starts no action

Realized, that the Map was not configured to offline so set it, but even that doesn't solve the problem

Two Problems:
* No indication, that Basemap is not set to take offline
* Download itself doesn't work

Data and screenshots attached to repro this problem.

Data and Maps - I could provide it, but too big (1.6 GB) to upload - just let me know

### Expected Behavior
* Information that the Basemap has to be enabled with download capabilities
* Download should work

### Map and Credentials
within acgis.com with the holistic_user10 Account from the HolisticLab
WebMap: Gewässer-Offline_20180405
Editlayer : Gewässer_LR_20180405
Basemap: BasiskarteTirol_20180405

### Steps to Reproduce
* Publish Basemap-Map as VTPK to Online - and enable also download capabilities
* Publish Map as Featureservice to Online with sync enabled
* Create in MapViewer a Map with it and save it
* Open the Map in Collector and zoom to layer - works
* Now take Map offline - Download Area button starts no Action

### Device Information
* Device: iPad
* OS Version: 11.2.6

**Comment by miaogeng** [comment]
We will look into this issue together with https://github.com/doug-m/CollectorAuroraTesting/issues/6.
