### ISSUE TITLE
Saving Collected Point

### ISSUE THREAD

**Issue by scottaolsen** [doug-m/CollectorAuroraTesting#29]
### Issue
While trying to save a collected point I received the following error: "Error: The type is not support by the domain"

### Expected Behavior
Should have saved the collected point.

### Map and Credentials

* Group Name: ESRICollector_bcfpd
* Map Name: MO-TF1 Training 2018-04-07

### Steps to Reproduce
Collect point
Fill out form
Submit 

### Device Information
* Device: IPAD Pro
* OS Version: 11.2.6 (15D100)

![image-1](https://user-images.githubusercontent.com/3643532/38385680-518d7bac-38c7-11e8-9a7b-29d6b3db3533.jpg)

**Comment by miaogeng** [comment]
As discussed with Scott, there seems to be an issue with the data. The way the service is setup. The coded values are as follows:
```codedValues: [
{
name: "Structure No Damage",
code: "StructureNoDamage"
},
{
name: "Structure Damaged",
code: "StructureDamaged"
},
{
name: "Structure Failed",
code: "StructureFailed"
},
{
name: "Structure Destroyed",
code: "StructureDestroyed"
}
]```
But the value in the templates or the one sent on submit has a number as a prefix.

For example one of the template is below.
```{
name: "01 Structure No Damage",
description: "",
drawingTool: "esriFeatureEditToolPoint",
prototype: {
attributes: {
Structure_Crew: null,
Structure_User: null,
Structure_Assessment: "01StructureNoDamage",
Structure_Type: "SFD",
Structure_Address: null,
Structure_Notes: null,
Structure_Team: "MO-TF1"
}
}
}```

It has `"01StructureNoDamage"` as the coded value with the extra number in the begining.

**Comment by miaogeng** [comment]
Invalid data
