### ISSUE TITLE
Error is not descriptive when submitting a point in build 2203 while current version (17.0.4) is descriptive in case where z value is enabled for shape field but no default value is specified

### ISSUE THREAD

**Issue by robogb** [doug-m/CollectorAuroraTesting#31]
### Issue

Error is not descriptive when submitting a point in build 2203 while in current version (17.0.4) is descriptive in case where z value is enabled for shape field but no default value is specified

### Expected Behavior

The error in current version (17.0.4) is descriptive to see what caused the failure, but build 2203 shows generic message which makes it difficult to find the cause ,hence it should be as descriptive as the current version
### Map and Credentials

* Group Name: Ess_Testing_Rashan
* Map Name: springs_Robel_version

### Steps to Reproduce
1. In ArcMap prepare a feature class that is z enabled 
2. In Service Editor, enable "Feature Access" and in "Feature Access" tab ignore "Apply default z-value" i.e leave unchceked
3. publish a feature service and create a webmap
4. open map in Collector for ArcGIS, try to submit a point.  Error "Unable to submit: unable to complete operation". 

*The current verison of Collector for ArcGIS display an error as "update failed. update could not be sent. The Shape must have a z value" 

### Device Information

* Device: i phone 5 s
* OS Version: 11.2.6

![img_4874](https://user-images.githubusercontent.com/38107532/38385755-9ded4ee6-38c7-11e8-9c53-f840b119ea13.PNG)
![img_4875](https://user-images.githubusercontent.com/38107532/38385756-9e09b770-38c7-11e8-9a22-44d42de587af.PNG)

**Comment by Kevin-GIS** [comment]
This issue has been addressed. The following messaging is displayed when creating feature w/out a default Z value defined:
![image-1](https://user-images.githubusercontent.com/24723464/44239343-b382c880-a16d-11e8-885b-3b131c3874a5.jpg)

Closing this issue.
