### ISSUE TITLE
"Current" map does not refresh if the map and underlying data were deleted

### ISSUE THREAD

**Issue by bethanyw** [doug-m/CollectorAuroraTesting#32]
### Issue
At the top of the map list is the "Current" map, which is the one that was last opened. If this map and underlying data is deleted (I used ArcGIS Online), refreshing the map list (using a long pull) does not update the current map. The map which was deleted is still listed and can be opened, even though it doesn't exist and let's you continue to try to add data. This will produce an error that says "Unable to Submit. Invalid URL."

This could be confusing for a field worker who may not know that an admin in AGOL deleted the map.

### Expected Behavior

The map should be removed from the "Current" map list and should not open if it no longer exists.

### Map and Credentials

* Group Name:
* Map Name:

### Steps to Reproduce

1) Create a map and hosted feature service data in ArcGIS Online
2) Open the map in Collector
3) Go back to the map list and see that it is listed as the "Current" map
4) Delete the map and hosted feature service data in ArcGIS Online
5) Use a long pull on the maps list to refresh this. The "Current" map is still listed as the map that was deleted and it can be opened up.
6) Close out of the app and reopen it. You will see an error that the map no longer exists. Then, if you go to the map list, there is no longer a current map.

The long pull refresh should be enough to remove this map from the "Current" map list.

### Device Information
* Device: iPhone 6+
* OS Version: 11.x

**Comment by miaogeng** [comment]
I can reproduce the issue. We will look into it. 
Note: sf 840

**Comment by Kevin-GIS** [comment]
This issue has been addressed. Closing this issue.
