### ISSUE TITLE
Selecting "Rename" after selecting the attachment to rename crashes the app

### ISSUE THREAD

**Issue by dmoorevt87** [doug-m/CollectorAuroraTesting#34]
### Issue
When attaching a photo, video, or file, selecting that attachment and selecting "Rename" will crash the application

### Expected Behavior
Clicking rename shouldn't crash the app

### Map and Credentials

* Group Name:
* Map Name:

### Steps to Reproduce
Take  a photo or attach a file. Select that file once it's attached. Press "rename". App should crash

### Device Information
* Device: iPhone 7 plus
* OS Version: 11.3

**Comment by miaogeng** [comment]
I can reproduce with this holistic build. But it doesn't happen in our internal build. Next holistic event, this issue should be fixed
