### ISSUE TITLE
App does not report the time of last sync correctly

### ISSUE THREAD

**Issue by bethanyw** [doug-m/CollectorAuroraTesting#36]
### Issue
App no longer reports the time of last sync. In previous versions of Collector, the app would report the time that the map was synced. Now, it looks like Collector only displays a date field, and no time field from the map list (this is confusing too). If you click "map details" for that area, we see that the "modified" time field is not properly updating with the time it was synced.

### Expected Behavior
Show time of last sync

### Map and Credentials

* Group Name:
* Map Name:

### Steps to Reproduce

1) Download a map for offline use
2) Sync map
3) No time reported in the map list view
4) Clicking the "Map Details" page shows that the modified time is not when it was last synced

### Device Information
* Device: iPhone 6+
* OS Version: 11.x

**Comment by doug-m** [comment]
The map details no longer are the appropriate location for this information, given that we have multiple areas that may have different sync dates.  This information will be available on the card for each offline area associated with the map.
