### ISSUE TITLE
Default LOD settings of taking raster basemap offline may result in bad resolution

### ISSUE THREAD

**Issue by mschenker** [doug-m/CollectorAuroraTesting#39]
### Issue
Taking a raster basemap (as part of a webmap) offline for a very small area results in an offline basemap with quite low resolution when using the default settings. It is not clear to the user, what level of detail "Street" means. Additionally, the names for LODs (such as Room or Building or Streets) only have a meaning in urban areas and do not necessarily have the same meaning in different parts of the world. The size of a building in NYC is probably much larger than the size of a street in some rural area.

### Expected Behavior
More feedback should be given to the user, such as a rough estimate of the download size, and also how this relates to the download size if the area was downloaded at full res (meaning the highest resolution of tiles defined in the basemap) 

### Steps to Reproduce
1. Create a webmap with a raster basemap, e.g. the Esri imagery basemap
2. Take a very small area of the webmap offline in Collector, leave the default settings
--> The resolution of the offline area is very likely much lower than expected.

### Device Information
* Device: iPad 4 Mini
* OS Version: 11.2.6

![badresolution](https://user-images.githubusercontent.com/738677/38387150-36df726a-3917-11e8-8a86-643578b5da51.png)

**Comment by caro7202** [comment]
Will be addressed in SF #856

**Comment by caro7202** [comment]
Addressed in next holistic June 18th
