### ISSUE TITLE
'Reload map' is not reflecting changes made to Web Map

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#4]
### Issue
'Reload map' is not reflecting changes made to Web Map

### Expected Behavior
When you make changes to a Web Map in ArcGIS Online, I would expect you to be able to exit the map in Collector, pull down to refresh, then open the map and see the changes reflected. I then tried to select the map options > reload map and this still did not reflect the changes. 

### Map and Credentials

* Group Name: April 5th: Collector Testing (Support)
* Map Name: Holistic Test Map

### Steps to Reproduce

1. Open current Map in Collector
2. Open Web Map in ArcGIS Online
3. Change the basemap and save
4. In Collector, exit map and refresh or reload
5. Changes will not be reflected
6. You must open a different map and then return to the original map to see the changes reflected

### Device Information
* Device: iPad mini
* OS Version: 11.2.1

**Comment by sbubka94** [comment]
If you are trying to add a new feature layer to the map, once you can view the features using the above workaround, you cannot interact with them in any way. 

The points or features will appear as "view only." All others layers are still accessible, except the newly added layer. So adding new layers to your web map later on for editing in Collector doesn't seem possible at the moment.

**Comment by miaogeng** [comment]
This should be addressed in next holistic. 

Note: This issue can be reproduced in holistic build but it doesn't happen to internal daily build
