### ISSUE TITLE
"Remove Area" also removes collected features

### ISSUE THREAD

**Issue by mschenker** [doug-m/CollectorAuroraTesting#41]
### Issue
The button to remove a webmap that was previously taken offline is called "Remove Area". Clicking it does also remove all previously collected features (if they have not been synched). 

### Expected Behavior
The button should be called "delete offline data" and additionally a warning should pop up if there are collected (unsynched) features that will be removed.

### Steps to Reproduce
1. Take a webmap offline
2. Collect Data
3. Remove area
--> The collected features are gone

### Device Information
* Device: iPad 4 MIni
* OS Version: 11.2.6

**Comment by claire-m-h** [comment]
I agree that this is confusing. I think it would be helpful if there was a warning that said something like "Unsynced edits will be deleted".

**Comment by li2504** [comment]
@mschenker Would a number next to the sync indicating the number of unsynced edit be helpful? Basically the old classic collector way of indicating pending sync.

**Comment by NeilMYoung** [comment]
I agree this is confusing as well. if the edits have not been synced data loss can occur far too easily as currently implemented.

**Comment by mschenker** [comment]
@NeilMYoung IDo you mean next to "*Sync" text on the menu (above "Map Details")? This would certainly help to remind the user that there is unsynced data. I do however not think that it helps regarding the confusion regarding the terminology, I do not think that it is clear enough that deleting an area also deletes the operational data. This should be clarified in a warning that pops up if the user clicks the button or as a text, e.g. "Remove Area (also deletes unsynched data)".

**Comment by miaogeng** [comment]
We will address this in future update. 
Note: Common 951

**Comment by aeveland** [comment]
Addressed in common #951

**Comment by caro7202** [comment]
Fix in June 18 holistic.
