### ISSUE TITLE
C16 - Year 0099 not handled correctly after editing

### ISSUE THREAD

**Issue by trichtl** [doug-m/CollectorAuroraTesting#43]
### Issue

Software: Collector
Version : Build 2203
OS      : iPad, iOS 11.2.6

Description:

publishing a WebMap from ArcGIS Pro and using datafields in collector - wihin collector I could define year 0099 for a date, which is displayed
fine and correctly.

When checking in the WebMap it shows correctly, but in th attribute table instead of 0099 it is shown as 1999.

* Publish WebMap with Sync Capabilities
* Edit the feature and change year to 0099
* Open webMap in MapViewer and attribute table you would see the difference

Attached data and screenshots

Gerhard "Luigi" tirchtl
### Map and Credentials
within ArcGIS Online Org of HolisticLab as User holistic_user10
WebMap: Dätumswertßä_20180405

### Steps to Reproduce
* Publish WebMap with Sync Capabilities
* Edit the feature and change year to 0099
* Open webMap in MapViewer and attribute table you would see the difference

### Device Information
* Device: iPad
* OS Version: iOS 11.2.6

[C16.zip](https://github.com/doug-m/CollectorAuroraTesting/files/1881650/C16.zip)

**Comment by Kevin-GIS** [comment]
Unable to reproduce this issue. According to the attached screenshot, this issue might be more related to AGOL, as oppose to Collector.

**Comment by trichtl** [comment]
HI retest the Problem with Build 2238 - Edits Shows now in Online correct also in the table as year 99 and not 1999 - however which you check the WebMap in ARcGIS Pro, it Labels correctly with 99, but in the Attributetable there is no date shown.
But now we try to take the edit data to take offline and as a result Collector is crashing - retried with a new collector session and happened again

**Comment by trichtl** [comment]
Crash might now be related to #53 as in this webmap and Featureservice are Special characters included (german) ßä (äöüÄÖÜß is the fullset of german characters)

**Comment by Kevin-GIS** [comment]
Thanks for the feedback @trichtl

I logged SF 904 for https://github.com/doug-m/CollectorAuroraTesting/issues/53. Hopefully it addresses both issues.

**Comment by trichtl** [comment]
Hi @Kevin-GIS - just retest this - because of the Format Change in Online it is now correctly displayed - also when consuming back in Pro - in Pro only the Attribute field didn't Show a date.

But as soon I want to take the map offline after the Change to a date below 100, which works fine online it Fails - not sure if we should log this now as a different issuee or work on this with that Problem?
