### ISSUE TITLE
Attachments don't show on feature with related tables

### ISSUE THREAD

**Issue by asmyrk** [doug-m/CollectorAuroraTesting#45]
### Issue
On points that do not have a relationship, I get the option to look at the details or the attachments.  On features that have a related table or on related tables with attachments, the only way I can view the attachments in Collector is to edit the feature.

### Expected Behavior
Should work the same as features without related tables.

### Map and Credentials
* Group Name: Asset Repair
* Map Name: PolesWithLightsInspection

### Steps to Reproduce
View the details of a pole with an attachment.

### Device Information
* Device: iPhone 7
* OS Version: 11.2.6

no related tables
![norelated](https://user-images.githubusercontent.com/31287579/38389879-ec0e5dbc-38dc-11e8-88cb-269f287b716e.jpg)

with related tables
![related](https://user-images.githubusercontent.com/31287579/38389895-fb21b9d4-38dc-11e8-9e6d-f16111c2c023.jpg)

**Comment by miaogeng** [comment]
I can reproduce the issue. We will look into it.

**Comment by miaogeng** [comment]
@asmyrk  We have looked into this issue. The reason is because 'Show feature attachments as links' setting is disabled in the popup setting. This is by design. If you enable the setting, you will see attachment while viewing the feature.

**Comment by asmyrk** [comment]
Oh of course.  Thank you Morgan.

Alison Walker
GPS/GIS Tech Services Manager
Frontier Precision, Inc.
154 1st Ave W | Jerome, ID | 83338
Direct: 208.595.1218
www.FrontierPrecision.com<http://www.frontierprecision.com/>
[FPI-Logo-263px][EPC-2018_Award_ToTheField-Sm]
