### ISSUE TITLE
Unable to select polygon on one map

### ISSUE THREAD

**Issue by claire-m-h** [doug-m/CollectorAuroraTesting#48]
### Issue
Unable to select polygons on one single web map

### Expected Behavior
Should be able to select features to try editing geometry or attributes

### Map and Credentials

* Group Name: April 5th: Collector Testing (Support)
* Map Name: RelatePopup

### Steps to Reproduce
Open RelatePopup
Try selecting polygon
Unable to select existing polygon
***Only able to reproduce with one web map
***Tried force closing Collector and still could not select points

### Device Information
* Device: iPhone 8
* OS Version: 11.2.6

**Comment by claire-m-h** [comment]
Able to add new features though

**Comment by Kevin-GIS** [comment]
The issue was that popups were disabled for both the feature layer and related table. Once they were enabled on the webmap, the issue was no longer reproducible.
