### ISSUE TITLE
Web map names of the ones that have offline areas downloaded do not show up when returning to web map list after opening an offline area

### ISSUE THREAD

**Issue by Shoumith** [doug-m/CollectorAuroraTesting#49]
### Issue
Web map names of the ones that have offline areas downloaded do not show up when returning to web map list after opening an offline area. It shows Area X instead. 

### Expected Behavior
The name of the web map should be shown, despite having offline areas downloaded. 

### Map and Credentials

* Group Name:
* Map Name:

### Steps to Reproduce
- Download an offline area for a map and open it.
- Go back to the web map list. Instead of showing the name of the web map, it shows Area X

### Device Information
* Device: iPhone 6s
* OS Version: 11.X

![img_0312](https://user-images.githubusercontent.com/9488766/38392194-81712b34-38db-11e8-9df3-d3bfb6a3807b.PNG)

**Comment by Kevin-GIS** [comment]
Should be addressed in SF 812.

**Comment by Kevin-GIS** [comment]
This issue has been addressed. Closing this issue.
