### ISSUE TITLE
When downloading Web Map with Vector Tile Basemap, the download extent is changing automatically. 

### ISSUE THREAD

**Issue by claire-m-h** [doug-m/CollectorAuroraTesting#5]
### Issue
 When downloading Web Map with Vector Tile Basemap, the download extent is changing automatically and erroneously.  

### Expected Behavior
I would expect the extent to stay the same until you change the Zoom Level, as it does with Raster Basemaps.
There is actually no option to select a Zoom Level when downloading

### Map and Credentials
* Group Name: April 5th: Collector Testing (Support)
* Map Name: Vector Tile Basemap- Offline

### Steps to Reproduce

1. Create Web Map with Vector Tile Basemap and sync-enabled, editable features
2. Open in Collector
3. Try adding offline area
4. Zoom to different extent- Map Extent changes unexpectedly 

### Device Information
* Device: iPhone 8
* OS Version: 11.2.6

[Video] (https://www.screencast.com/t/NzZCCcdkzH)

**Comment by sbubka94** [comment]
Another video to show behavior on another device (iPhone 7 Plus)

http://www.screencast.com/t/Q0vivszkbB

**Comment by claire-m-h** [comment]
Reproduced on iPad as well

**Comment by miaogeng** [comment]
Within the same extent and same LOD, different area can have different number of tiles in indexed tiling format. In ocean areas, It has quite small feature detail, the tile in a small scale can easily be used at larger scales.

**Comment by doug-m** [comment]
As discussed, this is by design.  The inset will update based on the vector tile limits available.
