### ISSUE TITLE
Labels created from domain fields do not display in Collector

### ISSUE THREAD

**Issue by r-ruval** [doug-m/CollectorAuroraTesting#50]
### Issue
Collector displays domain codes instead of descriptions when labels are applied based off a field with domains. 

### Expected Behavior
Collector should display label description, as displayed in ArcGIS Online map viewer. 

### Map and Credentials
* Group Name: April 5th: Collector Testing (Support)
* Map Name: Labeling Domains

### Steps to Reproduce
1. Add feature layer to ArcGIS Online Map Viewer
2. Click on the ellipsis(...) for the layer > Create labels. Set Label based off a field with domains assigned to it. 
3. Labels correctly display in Map Viewer.
4. Open web map in Collector > labels displaying domain code. 

### Device Information
* Device: Iphone 8 Plus
* OS Version: 11.2.6

**Comment by Kevin-GIS** [comment]
Existing issue SF 747
