### ISSUE TITLE
Default date+time values can cause values difficult to edit

### ISSUE THREAD

**Issue by jmmgeo** [doug-m/CollectorAuroraTesting#51]
### Issue
In the template for Manhole Inspections, the 'Inspection Date and Time' field is non-nullable and has some sort of default value. When you start a new inspection form, it defaults to 12/29/1899, 4:00PM and with the date+time picker, there is no way to pick the year discreetly and you'd have to scroll through 118 years of 365 days to get to 2018. I think it's fine that the date+time picker doesn't explicitly include a year column as it's probably likely that if someone is entering a time, that they're doing so for a relatively current timeperiod.

### Map and Credentials

* Group Name:
* Map Name:

### Steps to Reproduce
When looking at the properties of the service where this field exists, the following template information is indicated (created using the template for Manhole Inspections):

Templates: 
Name: Manhole Inspection
Description: 
Drawing Tool: esriFeatureEditToolNone
Prototype: 
Attributes: 
DateTime: -2209161600000
InspectionID:
ManholeNumber:
StreetNameNo:
SurveyedBy:
PreCleaning:
City:
CertificateNumber:
YearBuilt: 2000
InspectionStatus:
YearRenewed: 2000
### Device Information
* Device:
* OS Version:

**Comment by Kevin-GIS** [comment]
Existing issue SF 443
