### ISSUE TITLE
When using a map downloaded for offline use, you can still switch basemaps

### ISSUE THREAD

**Issue by bethanyw** [doug-m/CollectorAuroraTesting#52]
### Issue

When you have downloaded an offline area, you still have the option to switch basemaps. I did not have the time to configure Fiddler to see what kind of requests Fiddler was making, but I would assume it was making outbound requests to the ArcGIS Online basemaps. 

### Expected Behavior

I would expect that for a map area downloaded for offline use, that no requests should be made.

### Map and Credentials

* Group Name:
* Map Name:

### Steps to Reproduce

1) Create a sync enabled feature service, and add to a web map
2) Download for offline use
3) Click the ... icon in the upper right of the app > Click Basemaps
4) You have the option to switch basemaps, which seems contrary to the purpose of offline use. Additionally, after switching to another basemap, going back to the default basemap does not work. It only displays a white screen.

### Device Information
* Device: iPhone 6+
* OS Version: 11.x

**Comment by fcxagerr** [comment]
I noticed that when you select a different basemap when viewing an offline area map, you won't be able to load your Default basemap again in that session.

**Comment by bethanyw** [comment]
@fcxagerr, I saw the same. I submitted issue #55 for that. Good to know that it's not just me!

**Comment by NeilMYoung** [comment]
I noticed the same original issue of being albe to switch basemaps. iOS 11.2.6 iPhone 6

**Comment by mschenker** [comment]
Could be the same as #40

**Comment by caro7202** [comment]
Shouldnt be seeing online basemaps. We have an issue in place to address this.

**Comment by Kevin-GIS** [comment]
This has been addressed in SF 815
