### ISSUE TITLE
C18 - Download Area crashes always Collector

### ISSUE THREAD

**Issue by trichtl** [doug-m/CollectorAuroraTesting#53]
### Issue

Software: Collector
Version : Build 2203
OS      : iPad, iOS 11.2.6

Description:

publishing a WebMap from ArcGIS Pro and try to take it offline crashes Collector

* Publish WebMap with Sync Capabilities from ArcGIS Pro
* Take feature offline

==> Crash

Attached data and screenshots and also the crashdump from the iOS device

Gerhard "Luigi" tirchtl

### Expected Behavior
no Crash

### Map and Credentials
Availible within ArcGIS Online Org from Holistic Lab - user holistic_user10
* Map Name: Dätumswertßä_20180405

### Steps to Reproduce
* Publish WebMap with Sync Capabilities from ArcGIS Pro
* Take feature offline

==> Crash

### Device Information
* Device: iPad
* OS Version: iOS 11.2.6

[C18.zip](https://github.com/doug-m/CollectorAuroraTesting/files/1881925/C18.zip)

**Comment by Kevin-GIS** [comment]
Thanks for the feedback @trichtl 

I logged SF 904

**Comment by trichtl** [comment]
Tested now with Build 2284 - even with original date of 100 it Fails now to take offline - looks simlar to #13

**Comment by trichtl** [comment]
Good News - tested now with Build 2358 and now no longer a crash with Dates above 100, 

Bad New - as soon I edit online the data below 100 and I want to take offline it still crashes by Collector by taken map offline

**Comment by trichtl** [comment]
Still the Problem within Build 2440 with Dates below 100 - open Online WebMap, modify the date to 0094, Displays and sync fine online. Now take Map offline - Download Error - but not Crash of collector - maybe still an ArcGIS Online Issue - here the logging from collector:

02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Error downloading map: Error Domain=com.esri.arcgis.runtime.services.error Code=500 "Unable to create replica. Please check your parameters." UserInfo={NSLocalizedFailureReason=Exporting data for layer 0 failed., NSURL=https://services.arcgis.com/Ok7pjj1jT9rEneC7/arcgis/rest/services/D%C3%A4tumswert%C3%9F%C3%A4_WFL1/FeatureServer/jobs/218d20fc-c4c1-41a5-8534-d45874d25b17, responseJSON={
    error =    {
        code = 500;
        details =        (
            "Exporting data for layer 0 failed."
        );
        message = "Unable to create replica. Please check your parameters.";
    };
    lastUpdatedTime = 1538500028483;
    replicaID = "";
    replicaName = "";
    status = Failed;
    submissionTime = 1538500027593;
    targetType = client;
}, NSLocalizedDescription=Unable to create replica. Please check your parameters.} 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - job failed 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 3/12: Loading online map. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 9/12: Generate geodatabase: Job started. URL: https://services.arcgis.com/Ok7pjj1jT9rEneC7/arcgis/rest/services/Dätumswertßä_WFL1/FeatureServer 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 10/12: Generate geodatabase: Creating server job. URL: https://services.arcgis.com/Ok7pjj1jT9rEneC7/arcgis/rest/services/Dätumswertßä_WFL1/FeatureServer 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 8/12: Starting 2 sub-jobs. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 11/12: Export tile cache: Job started. URL: https://tiledbasemaps.arcgis.com/arcgis/rest/services/World_Topo_Map/MapServer 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 7/12: Prepare layer for offline:  Name: World Topographic Map URL: https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer Message: An alternate export enabled service will be used to take this layer offline URL: https://tiledbasemaps.arcgis.com/arcgis/rest/services/World_Topo_Map/MapServer 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 12/12: Export tile cache: Creating server job. URL: https://tiledbasemaps.arcgis.com/arcgis/rest/services/World_Topo_Map/MapServer 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 5/12: Fetching feature service infos. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 1/12: Job started. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 4/12: Loading online layers. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 6/12: Creating output directories. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 2/12: Loading offline map task. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Progress: 0.13 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 1/12: Job started. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 7/12: Prepare layer for offline:  Name: World Topographic Map URL: https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer Message: An alternate export enabled service will be used to take this layer offline URL: https://tiledbasemaps.arcgis.com/arcgis/rest/services/World_Topo_Map/MapServer 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 11/12: Export tile cache: Job started. URL: https://tiledbasemaps.arcgis.com/arcgis/rest/services/World_Topo_Map/MapServer 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 3/12: Loading online map. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 5/12: Fetching feature service infos. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 8/12: Starting 2 sub-jobs. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 6/12: Creating output directories. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 10/12: Generate geodatabase: Creating server job. URL: https://services.arcgis.com/Ok7pjj1jT9rEneC7/arcgis/rest/services/Dätumswertßä_WFL1/FeatureServer 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 9/12: Generate geodatabase: Job started. URL: https://services.arcgis.com/Ok7pjj1jT9rEneC7/arcgis/rest/services/Dätumswertßä_WFL1/FeatureServer 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 4/12: Loading online layers. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 12/12: Export tile cache: Creating server job. URL: https://tiledbasemaps.arcgis.com/arcgis/rest/services/World_Topo_Map/MapServer 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 2/12: Loading offline map task. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Progress: 0.12 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 2/12: Loading offline map task. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 5/8: Fetching feature service infos. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 4/12: Loading online layers. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - job started 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 11/12: Export tile cache: Job started. URL: https://tiledbasemaps.arcgis.com/arcgis/rest/services/World_Topo_Map/MapServer 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 7/12: Prepare layer for offline:  Name: World Topographic Map URL: https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer Message: An alternate export enabled service will be used to take this layer offline URL: https://tiledbasemaps.arcgis.com/arcgis/rest/services/World_Topo_Map/MapServer 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 6/12: Creating output directories. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 12/12: Export tile cache: Creating server job. URL: https://tiledbasemaps.arcgis.com/arcgis/rest/services/World_Topo_Map/MapServer 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 9/12: Generate geodatabase: Job started. URL: https://services.arcgis.com/Ok7pjj1jT9rEneC7/arcgis/rest/services/Dätumswertßä_WFL1/FeatureServer 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 8/12: Starting 2 sub-jobs. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 10/12: Generate geodatabase: Creating server job. URL: https://services.arcgis.com/Ok7pjj1jT9rEneC7/arcgis/rest/services/Dätumswertßä_WFL1/FeatureServer 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 1/12: Job started. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 5/12: Fetching feature service infos. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 3/12: Loading online map. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Progress: 0.11 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 8/10: Starting 2 sub-jobs. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 6/10: Creating output directories. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 4/10: Loading online layers. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 3/10: Loading online map. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 5/10: Fetching feature service infos. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 7/10: Prepare layer for offline:  Name: World Topographic Map URL: https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer Message: An alternate export enabled service will be used to take this layer offline URL: https://tiledbasemaps.arcgis.com/arcgis/rest/services/World_Topo_Map/MapServer 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - job started 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Progress: 0.1 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 2/10: Loading offline map task. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 1/8: Job started. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 6/8: Creating output directories. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 4/8: Loading online layers. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 3/8: Loading online map. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 2/8: Loading offline map task. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 1/8: Job started. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Progress: 0.08 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 3/5: Loading online map. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 1/5: Job started. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - job started 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 5/5: Fetching feature service infos. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 2/5: Loading offline map task. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 4/5: Loading online layers. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Progress: 0.06 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 1/4: Job started. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 4/4: Loading online layers. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 2/4: Loading offline map task. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - job started 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 3/4: Loading online map. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Progress: 0.04 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - job started 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - job started 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 2/3: Loading offline map task. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 3/3: Loading online map. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Message 1/3: Job started. 
02.10.18, 19:07 [BAE2AAF5-32BA-4D6D-BCF2-326F97D9522C] - Progress: 0.02 
02.10.18, 19:07 Calculating downloadable area for maxScale: 100.0, extent: AGSEnvelope: [(-13046255.663123, 4036616.696197), (-13046201.628977, 4036655.170510)], sr: 3857 
02.10.18, 19:07 raster tile count (iteration: 1 - extent: AGSEnvelope: [(-13046255.663123, 4036616.696197), (-13046201.628977, 4036655.170510)], sr: 3857 
02.10.18, 19:07 initial area requires < maxExportTileCount 
02.10.18, 19:07 Layer: World Topographic Map, tile count: 277, max: 150000 
02.10.18, 19:07 Layer: World Topographic Map maxExport: (0) 

Gerhard "Luigi" Trichtl

**Comment by Kevin-GIS** [comment]
This crashing issue has been addressed. Closing this issue.

**Comment by trichtl** [comment]
Thanks - worked now well in Build 2469
