### ISSUE TITLE
Can pan to areas outside of your offline web map; no download boundary

### ISSUE THREAD

**Issue by bethanyw** [doug-m/CollectorAuroraTesting#54]
### Issue

I noticed a confusing problem after downloading a map for offline use. You can pan and zoom to anywhere on the basemap, despite what your offline area was set as. Furthermore, there is no bounding box displayed on the map, so there is no way to easily pan back to your offline area. This also makes it difficult to know if you have accidentally strayed past your offline area (if you try to edit out of these bounds, you will get an error)

### Expected Behavior
1) I would expect not to be able to pan to areas outside of my offline area 

and 

2) I would expect a bounding box on the map to know where my offline area is

### Map and Credentials

* Group Name:
* Map Name:

### Steps to Reproduce

1) Create a sync enabled feature service and add it to a web map; download this for offline use in Collector
2) Switch basemaps; you can zoom to anywhere in the world you want, and you no longer see your bounding box to know what your original area was

### Device Information
* Device: iPhone 6+
* OS Version: 11.x

**Comment by Kevin-GIS** [comment]
For the issue regarding panning outside the offline extent, it could be similar to SF 758.

For the issue regarding switching basemaps and it no longer honoring your offline extent, its related to SF 815.

**Comment by li2504** [comment]
@bethanyw If you need to pan to the offline work area, the fastest way to do is to use the default bookmark. 

![basemap_offline_bookmark](https://user-images.githubusercontent.com/10201740/39077089-2758f160-44b4-11e8-9bab-d60c570f6691.jpg)

**Comment by Kevin-GIS** [comment]
This issue has been addressed. Closing this issue.
