### ISSUE TITLE
C19 - Linesymbol defined by attribute (size), not taken over to Collector

### ISSUE THREAD

**Issue by trichtl** [doug-m/CollectorAuroraTesting#57]
### Issue

Version: Build 2203
OS     : iPad, iOS 11.2.6

we have a Map within ArcGIS Pro defined linesymbol by attribute (size), publish this as WebMap with sync, which displays fine in WebMap with
symbology by attributes.

Now consume the same WebMap in Collector shows the line symbology all unique with the same size - so the symbol by attribute by size doesn't work.

Steps:
* Open ArcGIS Pro-Project
* Publish to ArcGIS Online with Sync enable
* Check symbol in MapViwer
* Open WebMap in Collector, linesymbols display in the same way and didn't respect symbology by attributes.

see attached screenshots and data to repro the problem.

Gerhard "Luigi" trichtl
### Expected Behavior
same symbolization as in ArcGIS and MapViewer

### Map and Credentials
Within ArcGIS Online Org of Holisitc Lab in User holistic_user10
* Map Name: LineSymbol_20180405

### Steps to Reproduce
* Open ArcGIS Pro-Project
* Publish to ArcGIS Online with Sync enable
* Check symbol in MapViwer
* Open WebMap in Collector, linesymbols display in the same way and didn't respect symbology by attributes.

### Device Information
* Device: iPad
* OS Version: iOS 11.2.6

[C19.zip](https://github.com/doug-m/CollectorAuroraTesting/files/1881967/C19.zip)

**Comment by Kevin-GIS** [comment]
Logged SF 743 issue.

**Comment by trichtl** [comment]
Hi, tested with Build 2284 and still not correctly displayed in Collector, but Shows corrects in ArcGIS Online Viewer and ArcGIS Pro - Problem might be that the linesize is vary by field, which has a Special fieldname (WITH²), means with a character outside of the ANSI 127 characters space.

**Comment by trichtl** [comment]
Hi @Kevin-GIS - just retested with Nov. 2019 Build and Display is now fine with Symbol scaling.

Problem is just now in taken offline (either Ad Hoc or Predevfined Aeas, because of the "invalid" characters, which is know - so we could close this Topic - thanks for fixing.
