### ISSUE TITLE
Data disappears after switching basemap from Vector Tile Basemap to Default Basemap and back to Vector Tile

### ISSUE THREAD

**Issue by claire-m-h** [doug-m/CollectorAuroraTesting#58]
### Issue
When switching between basemaps in a offline area map that originally used a Vector Basemap, the map's data disappears until your relaunch Collector. 

### Expected Behavior
I would expect the operational layers to remain. 

### Map and Credentials
* Group Name: April 5th: Collector Testing (Support)
* Map Name: Basemap Switch Test

### Steps to Reproduce

1. Create Web Map with Vector Tile Basemap
2. In Collector, download area for offline use (stay connected online though)
3. Open Area
4. Switch Basemap --> '...'  --> Basemap
5. Switch back to Vector Tile
6. Map is Blank

### Device Information
* Device: iPhone 8
* OS Version: 11.2.6

Video: https://www.screencast.com/t/8lgIjrss1E

**Comment by claire-m-h** [comment]
Possibly the same as #55

**Comment by li2504** [comment]
This issue has been linked to our internal GitHub bug tracking system. SF 815.

**Comment by Kevin-GIS** [comment]
@li2504 do we know this issue isn't reproducible when switching between multiple offline basemaps? Is it just because we're mixing online and offline basemaps when switching?

**Comment by Kevin-GIS** [comment]
@li2504 I logged a separate issue specifically for this use case and linked it to SF 815. The fix might be one in the same, but we'd need to verify that switching to and from the Default basemap works fine between offline basemaps.

**Comment by Kevin-GIS** [comment]
Not reproducible in the latest Beta build 2307
