### ISSUE TITLE
No error messages when entering an unacceptable values into certain user profile settings

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#59]
### Issue
There is no error message when entering an unacceptable value into the Collection Accuracy Distance requirement; it will just default to 0. There is the same behavior with the "Points to average" number under GPS averaging. For example, entering "1" or "a" will default to 5 points without telling you why. 

### Expected Behavior
I would expect an error message explaining the input is incorrect, and what the acceptable values may be. 

### Map and Credentials
N/A

### Steps to Reproduce

1. Open Profile
2. Accuracy
3. Enter value for distance that contains a letter or symbol
4. The value will set itself back to the default, or last correct value entered without a message

### Device Information
* Device: iPad Mini
* OS Version: 11.2.1

**Comment by aeveland** [comment]
Addressed in common #960

**Comment by caro7202** [comment]
Fix in next holistic build June 18
