### ISSUE TITLE
Vector tile download not working

### ISSUE THREAD

**Issue by rbruijning-esrinl** [doug-m/CollectorAuroraTesting#6]
### Issue
Map with vector tile basemap won't download (Projection: rd new)

### Expected Behavior
It should download the map when I push the download button

### Map and Credentials
 done
* Group Name: EGT Boominspectie
* Map Name: Boominspectie Aurora

### Steps to Reproduce
Download a map for offline use

### Device Information
* Device: 1st generation 12.9 inch iPad Pro
* OS Version: 11.2.6
[ScreenRecording_04-05-2018 19-24-33.zip](https://github.com/doug-m/CollectorAuroraTesting/files/1881068/ScreenRecording_04-05-2018.19-24-33.zip)

**Comment by mschenker** [comment]
Same here with Web Mercator in my case.
Group Name: EsriSwitzerland2AuroraHolisticApr5
Map Name: CollectionWebmap

**Comment by rbruijning-esrinl** [comment]
Issue #26

**Comment by rbruijning-esrinl** [comment]
Same issue as #26

**Comment by miaogeng** [comment]
I can reproduce the issue. We will look into this one.

**Comment by trichtl** [comment]
Hi, tested my Problem (C13 - ...., #26 ) and could take now the map offline with bookmarks without any Problem, also the original workflow, with taking a bigger area just with the Display is now starting and finally finish successfully - so in my opionion the Problem could be marked as fixed.

**Comment by Kevin-GIS** [comment]
This issue is no longer reproducible in the current Beta version of 2307. Closing this issue.
