### ISSUE TITLE
Lost the ability to edit existing features in an offline map

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#60]
### Issue
I had taken a map offline to collect some new data. At some point I tried to edit an existing feature and found there was no longer the option to "edit". Further investigation revealed there were no options for: edit, copy, delete, collect here, directions, compass, or add to my places. I synced the edits back successfully and found I was not able to edit in the live map either. After signing out of my profile and back in I was then able to edit again. 

I had checked to ensure no editing had been disabled. Other colleagues confirmed they were able to edit.

### Expected Behavior
I should be able to edit existing features unless editing capabilities have been modified. 

### Map and Credentials

* Group Name: April 5th: Collector Testing (Support)
* Map Name: HolisticTestMap

### Steps to Reproduce

No really sure at this point unfortunately. It could have been an issue with this particular download as I downloaded the same Web Map many times after without the same issue.

### Device Information
* Device: iPad Mini
* OS Version: 11.2.1

**Comment by caro7202** [comment]
I think this was caused by a bug where the popup action toolbar does not re-appear when switch from attachments tab to details tab, therefore the editing tools weren't showing up. We have addressed this issue and should not happen in the next holistic.

**Comment by Kevin-GIS** [comment]
This issue appears to have been addressed with SF 808
