### ISSUE TITLE
User settings not saved to profile when logging out

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#61]
### Issue
Settings are not saved to your profile when logging out. For example, change required accuracy or another setting then log out and log back in and it will reset to the default.

### Expected Behavior
These settings should be saved

### Map and Credentials
N/A

### Steps to Reproduce
Change required accuracy or another setting then log out and log back in and it will reset to the default

### Device Information
* Device: iPad Mini
* OS Version: 11.2.1

**Comment by caro7202** [comment]
sf #810

**Comment by caro7202** [comment]
This will be addressed in the next Holistic event 5/10
