### ISSUE TITLE
Unable to configure collect settings when collecting a point as you can in the classic app.

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#62]
### Issue
Unable to configure collect settings when collecting a point as you can in the classic app. (Equivalency)

### Expected Behavior
I was expecting to find this option when collecting a point. I think its nice to be able to change these settings while editing in a Web Map without having to return to the home menu. 

### Map and Credentials
N/A

### Device Information
* Device:
* OS Version:

**Comment by doug-m** [comment]
As this time we don't have any plans to expose the list of settings available.  Note that for streaming we do offer the ability to make changes to the streaming interval/method.  Similarly, we allow users to use a point outside of the location accuracy (by explicitly overriding).
