### ISSUE TITLE
Trying to submit a copied Related Record in an offline map throws an error, "Error, the data types are not compatible"

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#63]
### Issue
Trying to submit a Related Record copied from an existing Related Record in an offline map throws an error, "Error, the data types are not compatible". 

I narrowed the issue to a field of type "float" which has a domain. There is no problem submitting original related records, only when making a copy. It is not until I modify the value of this field that I can submit.

### Expected Behavior
You should be able to copy to new records and submit without error, especially when no changes are made to the fields. 

### Map and Credentials

* Group Name: 
April 5th: Collector Testing (Support)
* Map Name: HolisticTestMap

### Steps to Reproduce

1. Download offline map area
2. Select existing point feature with an existing inspection record (create one first if there are none)
3. Select Edit > select existing related record (inspection) > copy > submit
4. "Error, the data types are not compatible"
5. Change the value for field "test" and you can submit successfully

### Device Information
* Device: iPad Mini
* OS Version: 11.2.1

**Comment by li2504** [comment]
A bug has been submitted to our internal GitHub bug tracking system. Thank you for reporting the issue.

**Comment by li2504** [comment]
@colinlawr This issue has been fixed in the latest software daily build. You should see it in the next beta release. Thank you for reporting the issue.
