### ISSUE TITLE
Reload map doesnt seem to honor changes to Web Map

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#64]
### Issue
Reload map not honoring changes to Web Map, including symbology changes, popup configuration, bookmarks added, etc. It also brings you back to the spot you were before, i.e. the popup I had open would appear again after reloading map.

### Expected Behavior
Reload map should refresh everything in the map and include all changes made. I also believe it shouldnt bring you back to your same location and potential popup, as I would be expecting to start from defaults when reloading. 

### Map and Credentials

* Group Name: Collector Holistic 5/10
* Map Name: ZionFeatures

### Device Information
* Device: iPad mini
* OS Version: 11.2.1

**Comment by Kevin-GIS** [comment]
Thanks @colinlawr 

Logged SF 877

**Comment by caro7202** [comment]
Fixed in next holistic June 18
