### ISSUE TITLE
Unable to edit existing line features

### ISSUE THREAD

**Issue by clareprice** [doug-m/CollectorAuroraTesting#65]
### Issue
Unable to edit line feature after the feature created and de-selected on map.

### Expected Behavior
Should be able to edit the existing feature.

### Map and Credentials

* Group Name: Collector - Storm
* Map Name: Stormwater Network Editor - Copy

### Steps to Reproduce
- Create a new line feature (bioswale layer > open channel editing template)
- When the feature is saved and still selected on the map, the edit action is visible.
- De-select the feature from the map.
- Re-select the feature. Notice that the edit action is no longer available.

### Device Information
* Device: iPhone 6S
* OS Version: 11.3.1

**Comment by li2504** [comment]
@clareprice Could you please invite the user Collector4ArcGIS to the group "Collector - Storm"? This is the account we use to access the map that's mentioned in the bug report. Thank you!

**Comment by clareprice** [comment]
@li2504 This user has been added. Thanks!

**Comment by li2504** [comment]
@clareprice Thank you. I can reproduce this bug using your data.

**Comment by Kevin-GIS** [comment]
@clareprice I don't see the Stormwater Network Editor - Copy map shared with the Collector-Storm group. I only see the BMP Inventory & Assessment map. 

Is it possible for you to reshare that map?

**Comment by li2504** [comment]
@clareprice I would like to re-test this issue with the June 18th holistic build to see if it is still legit. The map, Stormwater Network Editor - Copy, you shared via Collector-Storm group is no longer available. 

Could you please share this map with us again? Thank you!

**Comment by Kevin-GIS** [comment]
Closing this issue at this point, as repro map and data are not available. Will reopen if this issue resurfaces or data becomes available.
