### ISSUE TITLE
Changing basemap in an offline map

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#66]
### Issue
You are able to change the basemap in an offline map; I am not sure you should be able to do this. I believe this was possible because I was still in a connected environment. 

Once I changed the basemap and attempted to return to the "default" I could no longer find my data. Switching to another basemap allowed me to find and zoom to it but again switching back to "default" I get a grey screen of empty tiles. 

### Expected Behavior
I wouldnt expect to be able to change my basemap in an offline map, unless I had sideloaded multiple basemaps to select from. Doing this appeared to have broken the default basemap.

### Map and Credentials

* Group Name: Collector Holistic 5/10
* Map Name: ZionFeatures

### Steps to Reproduce

Download offline area
In a connected environment, open the map and change the basemap to another option
Switch back to the default basemap
Tiles will not load and using default bookmark will not take you to the basemap either

**Upon deleting offline area I found there were now two listings for my map on the home screen. Clicking one of them crashed the app. Creating a separate issue

### Device Information
* Device: iPad mini
* OS Version: 11.2.1

![collector_basemap](https://user-images.githubusercontent.com/15009559/39884651-6085543e-543f-11e8-96c6-c9c9d51cd2f2.png)

**Comment by li2504** [comment]
@colinlawr Thank you for reporting the issue. We have two existing bugs logged in our development bug tracking system on this issue. SF 815 & SF 824.
