### ISSUE TITLE
"Cellular Downloads Disabled" message disappears immediately

### ISSUE THREAD

**Issue by RITI8169** [doug-m/CollectorAuroraTesting#67]
### Issue
When downloading an Offline Map on Cellular Data, a message appears "Cellular Downloads Disabled". This message pops up and disappears from the screen in a second and does not even give the user enough time to read it.

### Expected Behavior
This message should stay on the screen 

### Map and Credentials

* Group Name: Aurora Holistic

### Steps to Reproduce
Go to any of the Maps
Click on Add Offline Area
Click on Download

### Device Information
* Device: iPhone

**Comment by doug-m** [comment]
In this build we don't have the setting implemented for Download on WiFi only.  We'll be adding that shortly, and will review this once available.

**Comment by Kevin-GIS** [comment]
This has been addressed in SF 657
