### ISSUE TITLE
Changing basemap in an offline map 2 (CRASH/duplicates)

### ISSUE THREAD

**Issue by sbubka94** [doug-m/CollectorAuroraTesting#68]
### Issue
This is a follow up regarding the existing "Changing basemap in an offline map" issue. When you have an offline area and change the basemap, it seems to corrupt the offline area and render it unusable.

When you go back to the offline areas, remove the area, and return to the main menu, there are TWO of your original maps listed. 

The first time I noticed this and clicked one of the two maps, it crashed Collector.

Log: 
[Collector-2018-05-10-102651.ips.zip](https://github.com/doug-m/CollectorAuroraTesting/files/1992724/Collector-2018-05-10-102651.ips.zip)

I could not reproduce this after the first time, but @colinlawr also reproduced one time and could not reproduce after the first time.

### Expected Behavior
There should not be duplicate maps when returning to the main menu.

### Map and Credentials

* Group Name: Collector Holistic 5/10
* Map Name: ZionFeatures

### Steps to Reproduce

http://www.screencast.com/t/XIhR8dK7m

### Device Information
* Device: iPhone 7 Plus
* OS Version: iOS 11.3.1

**Comment by Kevin-GIS** [comment]
This issue has been addressed.
