### ISSUE TITLE
Adding a field in AGOL on a feature service does not show up in Collector

### ISSUE THREAD

**Issue by Shoumith** [doug-m/CollectorAuroraTesting#7]
### Issue
In the web map that was created for Collector containing a hosted feature service, I added a new field to test Workforce integration. However, this new field does not show up in Collector when collecting features even after the map was reloaded and also after signing out and signing in

### Expected Behavior
The added field should show up in the attribute panel when collecting a feature or updating an existing feature

### Map and Credentials

* Group Name: April 5th: Collector Testing (Support)
* Map Name: HolisticTestMap [Layer: Landmarkaction - Field: WF]

### Steps to Reproduce
In a map that is currently being used in Collector, go to ArcGIS Online and add a new field to one of the layers. Make sure the field is visible in the attribute table, save the map. Now reload the map in Collector. There is no change in the list of fields that is showing up in the attribute panel when collecting a new feature or updating an existing feature - i.e., the added field does not get listed there. 

### Device Information
* Device: iPhone 6s
* OS Version: 11.2.5

AGOL:
![image](https://user-images.githubusercontent.com/9488766/38381531-e82f66bc-38bb-11e8-9933-46ab22ee208d.png)

COLLECTOR:
![image-1](https://user-images.githubusercontent.com/9488766/38381612-2c9dde6e-38bc-11e8-9f70-495113a3eacc.jpg)

**Comment by miaogeng** [comment]
In AGOL side, using edit tool in ArcGIS Online map viewer, the field doesn't show on ArcGIS Online either. Once I configure the popup on the webmap and toggle on/off Display setting on WF filed. The field will show on ArcGIS Online edit tool. Collector will show this new field too but using alias name, which is empty.

After adding the field, by default, display and edit on the popup is turn on. Turn off display setting on the poup, click Edit tool in AGOL map view, the field still exists. I don't run into the scenario that the field doesn't show on Edit tool in AGOL map view.

**Comment by miaogeng** [comment]
Considering Collector matches AGOL behavior for this particular webmap and we can't recreate this type of webmap, we close this issue.
