### ISSUE TITLE
List of offline maps only displays the 'current map' vs. all my maps that are available offline

### ISSUE THREAD

**Issue by adgealleg** [doug-m/CollectorAuroraTesting#71]
### Issue
List of offline maps only displays the 'current map' vs. all my maps that are available offline

### Expected Behavior
I should see all my offline maps

### Map and Credentials

* Group Name: 
Aurora Holistic
* Map Name:

### Steps to Reproduce
See screen capture

### Device Information
* Device: iPhone 7
* OS Version: 11.3.1 (15E302)

[screen_capture.zip](https://github.com/doug-m/CollectorAuroraTesting/files/1992737/screen_capture.zip)

**Comment by Kevin-GIS** [comment]
Thanks for the feedback @adgealleg 

Logged SF 898

**Comment by Kevin-GIS** [comment]
This issue has been addressed. Closing this issue.
