### ISSUE TITLE
No offline maps are displayed in disconnected mode

### ISSUE THREAD

**Issue by RITI8169** [doug-m/CollectorAuroraTesting#75]
### Issue
When disconnected from the network, none of the offline maps for the user are displayed instead only the current map is displayed irrespective of whether it is offline or not.

### Expected Behavior
All my offline maps should be displayed in Collector when disconnected from the network

### Map and Credentials

* Group Name: Aurora Holistic
* Map Name: Hydrant Maintenance

### Device Information
* Device: iPhone 6S
* OS Version: 11

All Maps in Connected mode (with number of Offline Maps)
![collectoroffline1](https://user-images.githubusercontent.com/31448327/39886096-4b0de9b4-5443-11e8-94c0-3bd9b767534b.png)

Only the Current Map in Disconnected Mode (which is not even an Offline Map)
![collectoroffline2](https://user-images.githubusercontent.com/31448327/39886097-4b39bc24-5443-11e8-8aa1-b9c427795da4.png)

**Comment by Kevin-GIS** [comment]
Thanks for the feedback @RITI8169 

Logged SF 898
