### ISSUE TITLE
Map layers stop displaying when switching between maps

### ISSUE THREAD

**Issue by adgealleg** [doug-m/CollectorAuroraTesting#76]
### Issue
When I switch back and forth between maps, the second map eventually stops displaying

. Then I opened a 3rd map and the app crashed.

### Expected Behavior
Maps should load with all layers when switching between them

### Map and Credentials

* Group Name: Aurora Holistic
* Map Name:

### Steps to Reproduce
see screen capture video - [https://esri.box.com/s/4s9oubz0hkh9b39xd1hm3sr69e6mcp8d](https://esri.box.com/s/4s9oubz0hkh9b39xd1hm3sr69e6mcp8d)

### Device Information
* Device: iPhone 7
* OS Version: 11.3.1

I wasn't able to find the crash log

**Comment by kyliedonia** [comment]
Logged in team repo: SF 887

**Comment by Kevin-GIS** [comment]
Not reproducible in the Beta build 2307 - current version.
