### ISSUE TITLE
Showing related records by date field in UTC

### ISSUE THREAD

**Issue by clareprice** [doug-m/CollectorAuroraTesting#78]
### Issue
When a layer is configured to show a date field, when viewing related records the date field is presented in UTC versus local time/time attribute. The date/time attribute of the actual record is presenting the correct time.

### Expected Behavior
When viewing related records and sorted by a date field, the time should be presented as the time logged/attribute value versus UTC.

### Map and Credentials

* Group Name: Collector - Storm
* Map Name: BMP Inventory & Assessment

### Steps to Reproduce
- Open the BMP Inventory & Assessment map.
- Browse to a BMP feature, there is one near the Esri pond of type settling basin.
- Scroll through the attributes and view the related BMP Inspections table. 
- There is one record at this time with a date and time of 05/10/2018 6:25 PM
- Tap this inspection record to view the attributes of the table. Note that the recorded inspection date attribute is 5/10/2018 11:25 AM
### Device Information
* Device: iPhone 6
* OS Version: 11.3.1

![img_1298](https://user-images.githubusercontent.com/5611508/39887550-57c6bb28-5447-11e8-843c-b34b7c57f384.PNG)
![img_1297](https://user-images.githubusercontent.com/5611508/39887605-787992b4-5447-11e8-9705-e975e1c804c8.PNG)

**Comment by li2504** [comment]
@clareprice I can repro the issue you reported. I am going to label this issue as a Bug. We will port i to our internal bug tracking system. 

When I add a child record, the current time was the default for Inspection Date field, the record title however shows as UTC time. 
![utc](https://user-images.githubusercontent.com/10201740/39891612-df54398e-5452-11e8-9350-14ce6d87c140.png)

**Comment by doug-m** [comment]
SF #749

**Comment by caro7202** [comment]
This has been addressed. Should be in the next Holistic build June 18
