### ISSUE TITLE
Strange behavior with switching between online/offline basemaps

### ISSUE THREAD

**Issue by sbubka94** [doug-m/CollectorAuroraTesting#79]
### Issue
After you download an offline area, if you are still online and choose a basemap, obviously it will load and display for you, with some already noted issue. (See #68)

If you are viewing the basemap gallery and go offline while the gallery is open, the basemaps icons will continue to display. If you click on one that you viewed while online, it seems to be caching the basemap and showing pieces of it while offline.

### Expected Behavior
When you go offline, the basemap icons in the gallery should disappear and it should revert to your default basemap. There should be no caching happening since it provides a muddy user experience.

### Map and Credentials

* Group Name: Collector Holistic 5/10
* Map Name: ZionFeatures

### Steps to Reproduce

http://www.screencast.com/t/w0aWRmOX

### Device Information
* Device: iPhone 7 Plus
* OS Version: iOS 11.3.1

**Comment by caro7202** [comment]
This will be addressed in SF 815. Only on device basemap should be shown.

**Comment by Kevin-GIS** [comment]
This has been addressed.
