### ISSUE TITLE
Performance degradation-- downloading maps for offline use

### ISSUE THREAD

**Issue by bethanyw** [doug-m/CollectorAuroraTesting#8]
### Issue
I am seeing much longer amounts of time required to download a map for offline use compared to previous versions of Collector.

### Expected Behavior
When downloading an offline map, the download time is usually fairly quick. This depends on the extent and amount of data. For the same area in older versions of Collector, this took less than 1 minute. In Aurora, the map has been downloading for more than 20 minutes and has not completed.

### Map and Credentials

This is an internal machine using ArcGIS Enterprise (10.5.1). If you need access, let me know.

### Steps to Reproduce

1) Add a Portal hosted feature service (sync enabled) to a web map
2) Save the map and open this in Collector
3) Click to download the map; I chose a map that displayed the Charlotte metropolitan area. This has been downloading for more than 20 minutes.

### Device Information
* Device: iPhone 6+
* OS Version: 11.x

**Comment by miaogeng** [comment]
@bethanyw Here is another consideration of downloading time. That is the level of details. My sense about your test is Collector Aurora download more level of details, which cause longer time. From my test, I don't see the big difference.
