### ISSUE TITLE
Difficult to see "Done" and "Next" actions when editing attribute information

### ISSUE THREAD

**Issue by clareprice** [doug-m/CollectorAuroraTesting#83]
### Issue
When editing attribute information, it is difficult to see the "Done" and "Next" actions with the light grey color and white 

### Expected Behavior
A color for the text to make it more legible when editing attribute information.

### Map and Credentials

* Group Name:
* Map Name:
Any map, not specific to a single one.

### Steps to Reproduce
- Add a new feature and edit the attribute information. The light grey and the white make it difficult to see that these actions exist. Noticed this when both in direct sun and indoors.
![img_1299](https://user-images.githubusercontent.com/5611508/39888716-7fd832d8-544a-11e8-948b-efe65d6f0f52.PNG)

### Device Information
* Device: iPhone 6 S
* OS Version: 11.3.1

**Comment by aeveland** [comment]
This has been fixed.
