### ISSUE TITLE
Would like to be able to use in a vehicle or airplane will there be an option for accuracy?

### ISSUE THREAD

**Issue by kmalliso** [doug-m/CollectorAuroraTesting#87]
### Map and Credentials

* Group Name:
* Map Name:

### Device Information
* Device:
* OS Version:

**Comment by Kevin-GIS** [comment]
Hi @kmalliso could you please elaborate on the accuracy you're referring to?

In the Settings you can define a required accuracy value to filter out locations that have poor accuracy. You can also define a location provider. By default its the devices Integrated Receiver, however you can use external Bluetooth devices also.

**Comment by Kevin-GIS** [comment]
Hi @kmalliso I just wanted to follow-up with you to see if you had received my last comment?

**Comment by Kevin-GIS** [comment]
I am going to close this issue for the time being, until more information becomes available.

**Comment by kmalliso** [comment]
Sorry doug I have been swamped at work, doing a detail with predictive services. This was added since we have both fixed and rotor wings up with people in them collecting info is there a way to choose your accuracy so that it is possible to swag a line early on?

Also we have the gotenna pro’s that I was talking to you about would it be possible to integrate the ability to send location information from collector with them?

Thank you!
Kristen
