### ISSUE TITLE
5/10 holistic feedback from Alison Walker: Show attachments in identify pupup

### ISSUE THREAD

**Issue by li2504** [doug-m/CollectorAuroraTesting#89]
### Issue
Alison Walker posted in the holistic-may-10 Slack channel ...

"I also don't like that I can't see my photos attached to a feature unless I'm editing that feature."

### Map and Credentials

* Group Name:
* Map Name:

### Device Information
* Device:
* OS Version:

**Comment by kyliedonia** [comment]
I'm unable to reproduce this. When I open a layer with attachments, I can see them in the "Attached" tab in the popup when not editing. Could we get data to repro this?

**Comment by kyliedonia** [comment]
Alison confirmed that the popup wasn't set to show attachments.
