### ISSUE TITLE
Collector accuracy is not matching Trimble's accuracy

### ISSUE THREAD

**Issue by dmoorevt87** [doug-m/CollectorAuroraTesting#9]
### Issue
Even though the accuracy in the trimble r1 is between 5-6.1 meters, the accuracy in Collector never dips below 8.7. For this test, I am just using integrated receiver options and connecting the trimble over bluetooth since the gps will override the internal location services. Aka the workflow used before Collector 10.4

### Map and Credentials

* Group Name:
* Map Name:

### Device Information
* Device:iPhone 7 plus
* OS Version:iOS 11.3

**Comment by Kevin-GIS** [comment]
SF 783 has been addressed. Aurora supports connecting to external Trimble receivers.
