### ISSUE TITLE
Launching Collector via custom url scheme from Survey123 crashes the app

### ISSUE THREAD

**Issue by sbubka94** [doug-m/CollectorAuroraTesting#91]
### Issue
When a link is included in your survey from users to launch the Collector app, it crashes before loading the map. Same behavior as #90 

No parameters were passed - just a simple call to launch the app using : 

<a href="arcgis-collector://?itemID=5d9b159db9f744fa82b3ed12aa6d03a1">Launch Collector</a>

### Expected Behavior
You should be able to launch Collector using the url scheme

### Map and Credentials

* Group Name: Collector Holistic 5/10
* Map Name: (Feature layer + Form) - Damage Survey

### Steps to Reproduce

Here is the form:
[Damage Survey.xlsx](https://github.com/doug-m/CollectorAuroraTesting/files/1993296/Damage.Survey.xlsx)

The survey has been shared to the group, so you should have access from Collector4ArcGIS account:
https://survey123.arcgis.com/share/5d988367d170488797b39bd363d16863?open=native

Click the Launch Collector hyperlink and the app will crash

### Device Information
* Device: iPhone 7 +
* OS Version: iOS 11.3.1

**Comment by kyliedonia** [comment]
Might be SF #869

**Comment by Kevin-GIS** [comment]
This issue has been addressed. Closing this issue.
