### ISSUE TITLE
When collecting features while offline but with no offline area defined I attempted to add features and got the expected message that I'm offline, yet when I click cancel and 'discard' the points still appear on the map and give a false impression that data was still collected but they don't sync back or ever get submitted

### ISSUE THREAD

**Issue by adgealleg** [doug-m/CollectorAuroraTesting#94]
### Issue
When collecting features while offline but with no offline area defined I attempted to add features and got the expected message that I'm offline, yet when I click cancel and 'discard' the points still appear on the map and give a false impression that data was still collected but they don't sync back or ever get submitted

### Expected Behavior
Would expect that clicking discard would actually discard the point

### Map and Credentials

* Group Name: Aurora Holistic
* Map Name: Ground Control

### Steps to Reproduce
https://esri.box.com/s/f804qkus9082xdqg2ll7fv1d4hxbe6vz

### Device Information
* Device: iPhone 7
* OS Version: 11.3.1

**Comment by Kevin-GIS** [comment]
This issue has been addressed.
