### ISSUE TITLE
Issues with the compass icon

### ISSUE THREAD

**Issue by colinlawr** [doug-m/CollectorAuroraTesting#96]
### Issue
When rotating the view in any map, the compass icon will appear overlapping with the my location icon. It will re-adjust it self to its normal position shortly after. In addition, after rotating, when clicking it will correctly orient back north but the directional arrow will not adjust correctly. After this it seems to disappear unexpectedly at times as well. 

### Expected Behavior
The icon should appear in its correct location and not overlap any other icons. It should also point to the North when clicking to orient your map. 

### Map and Credentials
N/A, used try it now maps to repro

### Steps to Reproduce
1. Open and map
2. Rotate the map using two fingers
3. The compass badge will appear overlapping the My Location icon
4. It will re-adjust it self after a few seconds
5. Try clicking the icon to orient north again. This will work but the arrow will not align correctly
6. Occasionally the icon would disappear altoghether when subsequently rotating the map more

### Device Information
* Device: Iphone 6s
* OS Version: 11.3

**Comment by caro7202** [comment]
Logged in SF 972

**Comment by miaogeng** [comment]
This should not happen in next holistic event or beta. This should be fixed.
